
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AchievementConfig : BeanBase
    {
        public AchievementConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Condition = Condition.DeserializeCondition(_buf);

            PostInit();
        }

        public static AchievementConfig DeserializeAchievementConfig(ByteBuf _buf)
        {
            return new AchievementConfig(_buf);
        }

        /// <summary>
        /// 成就id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 成就名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 成就描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 成就条件
        /// </summary>
        public readonly Condition Condition;

        public const int __ID__ = -714023119;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "Condition:" + Condition + ","
            + "}";
        }

        partial void PostInit();
    }
}
