
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum ActionType
    {
        /// <summary>
        /// 修改属性行为
        /// </summary>
        ActionType_ModifyProperty = 1,

        /// <summary>
        /// 伤害行为
        /// </summary>
        ActionType_Damage = 2,

        /// <summary>
        /// 子弹行为
        /// </summary>
        ActionType_CastBullet = 3,

        /// <summary>
        /// 移动到目标行为
        /// </summary>
        ActionType_MoveToTarget = 4,

        /// <summary>
        /// 释放子技能行为
        /// </summary>
        ActionType_CastSubcast = 5,

        /// <summary>
        /// 吸引行为
        /// </summary>
        ActionType_Attract = 6,

        /// <summary>
        /// 击飞行为
        /// </summary>
        ActionType_HitFly = 7,

        /// <summary>
        /// 陷阱行为
        /// </summary>
        ActionType_CastTrap = 8,

    }
}
