
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AIConfig : BeanBase
    {
        public AIConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AIInfo = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AIInfo.Add(_e0);}}

            PostInit();
        }

        public static AIConfig DeserializeAIConfig(ByteBuf _buf)
        {
            return new AIConfig(_buf);
        }

        /// <summary>
        /// AI编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// AI节点
        /// </summary>
        public readonly System.Collections.Generic.List<int> AIInfo;

        public const int __ID__ = -294143606;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "AIInfo:" + Luban.StringUtil.CollectionToString(AIInfo) + ","
            + "}";
        }

        partial void PostInit();
    }
}
