
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 战斗属性克制
    /// </summary>
    [Config]
    public partial class BattleAttributeConfigCategory : Singleton<BattleAttributeConfigCategory>
    {
        private readonly List<BattleAttributeConfig> _dataList;

        private Dictionary<(BattleAttribute, BattleAttribute), BattleAttributeConfig> _dataMapUnion;

        public BattleAttributeConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<BattleAttributeConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                BattleAttributeConfig _v;
                _v = BattleAttributeConfig.DeserializeBattleAttributeConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(BattleAttribute, BattleAttribute), BattleAttributeConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.Id, _v.DestAttribute), _v);
            }
        }

        public List<BattleAttributeConfig> DataList => _dataList;

        public BattleAttributeConfig Get(BattleAttribute Id, BattleAttribute DestAttribute) => _dataMapUnion.TryGetValue((Id, DestAttribute), out BattleAttributeConfig __v) ? __v : null;

        partial void PostInit();
    }
}
