
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum BattlePosition
    {
        /// <summary>
        /// 左上
        /// </summary>
        BattlePosition_LeftTop = 1,

        /// <summary>
        /// 左中
        /// </summary>
        BattlePosition_LeftMiddle = 2,

        /// <summary>
        /// 左下
        /// </summary>
        BattlePosition_LeftBottom = 3,

        /// <summary>
        /// 中上
        /// </summary>
        BattlePosition_TopMiddle = 4,

        /// <summary>
        /// 中
        /// </summary>
        BattlePosition_Middle = 5,

        /// <summary>
        /// 中下
        /// </summary>
        BattlePosition_BottomMiddle = 6,

        /// <summary>
        /// 右上
        /// </summary>
        BattlePosition_RightTop = 7,

        /// <summary>
        /// 右中
        /// </summary>
        BattlePosition_RightMiddle = 8,

        /// <summary>
        /// 右下
        /// </summary>
        BattlePosition_RightBottom = 9,

    }
}
