
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 玩家初始场景配置
    /// </summary>
    [Config]
    public partial class BornSceneConfigCategory : Singleton<BornSceneConfigCategory>
    {
        private readonly Dictionary<RaceType, BornSceneConfig> _dataMap;
        private readonly List<BornSceneConfig> _dataList;

        public BornSceneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<RaceType, BornSceneConfig>();
            _dataList = new List<BornSceneConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BornSceneConfig _v;
                _v = BornSceneConfig.DeserializeBornSceneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<RaceType, BornSceneConfig> DataMap => _dataMap;
        public List<BornSceneConfig> DataList => _dataList;

        public BornSceneConfig GetOrDefault(RaceType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BornSceneConfig Get(RaceType key) => _dataMap[key];
        public BornSceneConfig this[RaceType key] => _dataMap[key];

        partial void PostInit();
    }
}
