
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum BuffActionType
    {
        /// <summary>
        /// 变羊
        /// </summary>
        BuffActionType_Yang = 1,

        /// <summary>
        /// 修改后处理
        /// </summary>
        BuffActionType_Volume = 2,

    }
}
