
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : BeanBase
    {
        public BuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            BuffProperty = (BuffProperty)_buf.ReadInt();
            ContinueTime = _buf.ReadLong();
            NotifyType = (MessageNotifyType)_buf.ReadInt();
            Tick = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AddActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AddActions.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TickActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TickActions.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RemoveActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemoveActions.Add(_e0);}}
            Fx = _buf.ReadString();

            PostInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// buff名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// buff描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// buff类型属性
        /// </summary>
        public readonly BuffProperty BuffProperty;

        /// <summary>
        /// 持续时长（ms）
        /// </summary>
        public readonly long ContinueTime;

        /// <summary>
        /// 通知客户端方式
        /// </summary>
        public readonly MessageNotifyType NotifyType;

        /// <summary>
        /// buff生效间隔
        /// </summary>
        public readonly int Tick;

        /// <summary>
        /// buff添加行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> AddActions;

        /// <summary>
        /// buff心跳行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> TickActions;

        /// <summary>
        /// buff移除行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> RemoveActions;

        /// <summary>
        /// buff特效
        /// </summary>
        public readonly string Fx;

        public const int __ID__ = -1370631787;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "BuffProperty:" + BuffProperty + ","
            + "ContinueTime:" + ContinueTime + ","
            + "NotifyType:" + NotifyType + ","
            + "Tick:" + Tick + ","
            + "AddActions:" + Luban.StringUtil.CollectionToString(AddActions) + ","
            + "TickActions:" + Luban.StringUtil.CollectionToString(TickActions) + ","
            + "RemoveActions:" + Luban.StringUtil.CollectionToString(RemoveActions) + ","
            + "Fx:" + Fx + ","
            + "}";
        }

        partial void PostInit();
    }
}
