
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffTriggerInfo : BeanBase
    {
        public BuffTriggerInfo(ByteBuf _buf)
        {
            AddAction = _buf.ReadInt();
            TickAction = _buf.ReadInt();
            RemoveAction = _buf.ReadInt();

            PostInit();
        }

        public static BuffTriggerInfo DeserializeBuffTriggerInfo(ByteBuf _buf)
        {
            return new BuffTriggerInfo(_buf);
        }

        public readonly int AddAction;

        public ActionConfig AddActionConfig => ActionConfigCategory.Instance.GetOrDefault(AddAction);

        public readonly int TickAction;

        public ActionConfig TickActionConfig => ActionConfigCategory.Instance.GetOrDefault(TickAction);

        public readonly int RemoveAction;

        public ActionConfig RemoveActionConfig => ActionConfigCategory.Instance.GetOrDefault(RemoveAction);

        public const int __ID__ = -1195818989;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "AddAction:" + AddAction + ","
            + "TickAction:" + TickAction + ","
            + "RemoveAction:" + RemoveAction + ","
            + "}";
        }

        partial void PostInit();
    }
}
