
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class BuffParams : BeanBase
    {
        public BuffParams(ByteBuf _buf)
        {

            PostInit();
        }

        public static BuffParams DeserializeBuffParams(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case BuffModifyPropertyParams.__ID__: return new BuffModifyPropertyParams(_buf);
                case BuffControlParams.__ID__: return new BuffControlParams(_buf);
                case BuffDotParams.__ID__: return new BuffDotParams(_buf);
                case BuffActionParams.__ID__: return new BuffActionParams(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
