
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum BuffControlType
    {
        /// <summary>
        /// 眩晕
        /// </summary>
        BuffControlType_Xuanyun = 1,

        /// <summary>
        /// 沉默
        /// </summary>
        BuffControlType_Chenmo = 2,

        /// <summary>
        /// 致盲
        /// </summary>
        BuffControlType_Zhimang = 3,

    }
}
