
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : BeanBase
    {
        public BuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = (BuffType)_buf.ReadInt();
            ContinueTime = _buf.ReadLong();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Parameters = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Parameters.Add(_e0);}}

            PostInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly BuffType Type;

        /// <summary>
        /// 持续时长（ms）
        /// </summary>
        public readonly long ContinueTime;

        /// <summary>
        /// 参数列表
        /// </summary>
        public readonly System.Collections.Generic.List<int> Parameters;

        public const int __ID__ = -1370631787;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "ContinueTime:" + ContinueTime + ","
            + "Parameters:" + Luban.StringUtil.CollectionToString(Parameters) + ","
            + "}";
        }

        partial void PostInit();
    }
}
