
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuildingLevelInfo : BeanBase
    {
        public BuildingLevelInfo(ByteBuf _buf)
        {
            ProduceCurrencyType = (CurrencyType)_buf.ReadInt();
            ProduceCurrencyValue = _buf.ReadLong();
            UpgradeCurrencyType = (CurrencyType)_buf.ReadInt();
            UpgradeCurrencyValue = _buf.ReadLong();
            LimitBuildingConfig = _buf.ReadInt();
            LimitLevel = _buf.ReadInt();

            PostInit();
        }

        public static BuildingLevelInfo DeserializeBuildingLevelInfo(ByteBuf _buf)
        {
            return new BuildingLevelInfo(_buf);
        }

        public readonly CurrencyType ProduceCurrencyType;

        public readonly long ProduceCurrencyValue;

        public readonly CurrencyType UpgradeCurrencyType;

        public readonly long UpgradeCurrencyValue;

        public readonly int LimitBuildingConfig;

        public readonly int LimitLevel;

        public const int __ID__ = -1281938978;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "ProduceCurrencyType:" + ProduceCurrencyType + ","
            + "ProduceCurrencyValue:" + ProduceCurrencyValue + ","
            + "UpgradeCurrencyType:" + UpgradeCurrencyType + ","
            + "UpgradeCurrencyValue:" + UpgradeCurrencyValue + ","
            + "LimitBuildingConfig:" + LimitBuildingConfig + ","
            + "LimitLevel:" + LimitLevel + ","
            + "}";
        }

        partial void PostInit();
    }
}
