
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuildingConfig : BeanBase
    {
        public BuildingConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Limit = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Produce = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Produce.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpgradeConsume = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); UpgradeConsume.Add(_e0);}}

            PostInit();
        }

        public static BuildingConfig DeserializeBuildingConfig(ByteBuf _buf)
        {
            return new BuildingConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 可建造个数限制
        /// </summary>
        public readonly int Limit;

        /// <summary>
        /// 每秒产出
        /// </summary>
        public readonly System.Collections.Generic.List<int> Produce;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public readonly System.Collections.Generic.List<int> UpgradeConsume;

        public const int __ID__ = -701401290;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Limit:" + Limit + ","
            + "Produce:" + Luban.StringUtil.CollectionToString(Produce) + ","
            + "UpgradeConsume:" + Luban.StringUtil.CollectionToString(UpgradeConsume) + ","
            + "}";
        }

        partial void PostInit();
    }
}
