
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 建筑配置表
    /// </summary>
    [Config]
    public partial class BuildingConfigCategory : Singleton<BuildingConfigCategory>
    {
        private readonly Dictionary<int, BuildingConfig> _dataMap;
        private readonly List<BuildingConfig> _dataList;

        public BuildingConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BuildingConfig>();
            _dataList = new List<BuildingConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BuildingConfig _v;
                _v = BuildingConfig.DeserializeBuildingConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BuildingConfig> DataMap => _dataMap;
        public List<BuildingConfig> DataList => _dataList;

        public BuildingConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BuildingConfig Get(int key) => _dataMap[key];
        public BuildingConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
