
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BulletCycleShape : BulletShape
    {
        public BulletCycleShape(ByteBuf _buf) : base(_buf) 
        {
            Radius = _buf.ReadInt();

            PostInit();
        }

        public static BulletCycleShape DeserializeBulletCycleShape(ByteBuf _buf)
        {
            return new BulletCycleShape(_buf);
        }

        public readonly int Radius;

        public const int __ID__ = -732688099;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Radius:" + Radius + ","
            + "}";
        }

        partial void PostInit();
    }
}
