
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class BulletShape : BeanBase
    {
        public BulletShape(ByteBuf _buf)
        {

            PostInit();
        }

        public static BulletShape DeserializeBulletShape(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case BulletCycleShape.__ID__: return new BulletCycleShape(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
