
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 子弹配置表
    /// </summary>
    [Config]
    public partial class BulletConfigCategory : Singleton<BulletConfigCategory>
    {
        private readonly Dictionary<int, BulletConfig> _dataMap;
        private readonly List<BulletConfig> _dataList;

        public BulletConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BulletConfig>();
            _dataList = new List<BulletConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BulletConfig _v;
                _v = BulletConfig.DeserializeBulletConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BulletConfig> DataMap => _dataMap;
        public List<BulletConfig> DataList => _dataList;

        public BulletConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BulletConfig Get(int key) => _dataMap[key];
        public BulletConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
