
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 技能释放配置
    /// </summary>
    [Config]
    public partial class CastConfigCategory : Singleton<CastConfigCategory>
    {
        private readonly Dictionary<int, CastConfig> _dataMap;
        private readonly List<CastConfig> _dataList;

        public CastConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CastConfig>();
            _dataList = new List<CastConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CastConfig _v;
                _v = CastConfig.DeserializeCastConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CastConfig> DataMap => _dataMap;
        public List<CastConfig> DataList => _dataList;

        public CastConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public CastConfig Get(int key) => _dataMap[key];
        public CastConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
