
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastForwardRect : CastSelectTargetsParams
    {
        public CastForwardRect(ByteBuf _buf) : base(_buf) 
        {
            Width = _buf.ReadInt();
            Height = _buf.ReadInt();
            Counter = _buf.ReadInt();

            PostInit();
        }

        public static CastForwardRect DeserializeCastForwardRect(ByteBuf _buf)
        {
            return new CastForwardRect(_buf);
        }

        public readonly int Width;

        public readonly int Height;

        public readonly int Counter;

        public const int __ID__ = -2134626966;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Width:" + Width + ","
            + "Height:" + Height + ","
            + "Counter:" + Counter + ","
            + "}";
        }

        partial void PostInit();
    }
}
