
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 客户端技能配置
    /// </summary>
    [Config]
    public partial class CastClientConfigCategory : Singleton<CastClientConfigCategory>
    {
        private readonly Dictionary<int, CastClientConfig> _dataMap;
        private readonly List<CastClientConfig> _dataList;

        public CastClientConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CastClientConfig>();
            _dataList = new List<CastClientConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CastClientConfig _v;
                _v = CastClientConfig.DeserializeCastClientConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CastClientConfig> DataMap => _dataMap;
        public List<CastClientConfig> DataList => _dataList;

        public CastClientConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public CastClientConfig Get(int key) => _dataMap[key];
        public CastClientConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
