
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastConfig : BeanBase
    {
        public CastConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            TotalTime = _buf.ReadLong();
            SelectTargetType = (SelectTargetType)_buf.ReadInt();
            CastCooldown = _buf.ReadInt();
            if(_buf.ReadBool()){ Casting = _buf.ReadInt(); } else { Casting = null; }
            SelectTargetsParams = SelectTargetsParams.DeserializeSelectTargetsParams(_buf);
            NotifyType = (MessageNotifyType)_buf.ReadInt();
            CastStartAnimation = _buf.ReadString();
            CastHitAnimation = _buf.ReadString();

            PostInit();
        }

        public static CastConfig DeserializeCastConfig(ByteBuf _buf)
        {
            return new CastConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 技能总时长
        /// </summary>
        public readonly long TotalTime;

        /// <summary>
        /// 选择目标类型
        /// </summary>
        public readonly SelectTargetType SelectTargetType;

        /// <summary>
        /// 技能释放CD
        /// </summary>
        public readonly int CastCooldown;

        /// <summary>
        /// 持续施法
        /// </summary>
        public readonly int? Casting;

        public readonly SelectTargetsParams SelectTargetsParams;

        /// <summary>
        /// 通知客户端方式
        /// </summary>
        public readonly MessageNotifyType NotifyType;

        /// <summary>
        /// 技能起手动画
        /// </summary>
        public readonly string CastStartAnimation;

        /// <summary>
        /// 技能受击动画
        /// </summary>
        public readonly string CastHitAnimation;

        public const int __ID__ = 944053121;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "TotalTime:" + TotalTime + ","
            + "SelectTargetType:" + SelectTargetType + ","
            + "CastCooldown:" + CastCooldown + ","
            + "Casting:" + Casting + ","
            + "SelectTargetsParams:" + SelectTargetsParams + ","
            + "NotifyType:" + NotifyType + ","
            + "CastStartAnimation:" + CastStartAnimation + ","
            + "CastHitAnimation:" + CastHitAnimation + ","
            + "}";
        }

        partial void PostInit();
    }
}
