
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum CharacterType
    {
        /// <summary>
        /// 战士
        /// </summary>
        CharacterType_Warrior = 1,

        /// <summary>
        /// 骑士
        /// </summary>
        CharacterType_Paladin = 2,

        /// <summary>
        /// 法师
        /// </summary>
        CharacterType_Mage = 4,

        /// <summary>
        /// 牧师
        /// </summary>
        CharacterType_Priest = 8,

        /// <summary>
        /// 盗贼
        /// </summary>
        CharacterType_Rogue = 16,

        /// <summary>
        /// 德鲁伊
        /// </summary>
        CharacterType_Druid = 32,

        /// <summary>
        /// 猎人
        /// </summary>
        CharacterType_Hunter = 64,

        /// <summary>
        /// 术士
        /// </summary>
        CharacterType_Warlock = 128,

        /// <summary>
        /// 萨满
        /// </summary>
        CharacterType_Shaman = 256,

        /// <summary>
        /// 死亡骑士
        /// </summary>
        CharacterType_DarkKnight = 512,

    }
}
