
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ChargeConfig : BeanBase
    {
        public ChargeConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Price = _buf.ReadLong();

            PostInit();
        }

        public static ChargeConfig DeserializeChargeConfig(ByteBuf _buf)
        {
            return new ChargeConfig(_buf);
        }

        /// <summary>
        /// 商品编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 价格
        /// </summary>
        public readonly long Price;

        public const int __ID__ = 969346870;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Price:" + Price + ","
            + "}";
        }

        partial void PostInit();
    }
}
