
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 创角初始表
    /// </summary>
    [Config]
    public partial class CreateRoleConfigCategory : Singleton<CreateRoleConfigCategory>
    {
        private readonly Dictionary<CharacterType, CreateRoleConfig> _dataMap;
        private readonly List<CreateRoleConfig> _dataList;

        public CreateRoleConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<CharacterType, CreateRoleConfig>();
            _dataList = new List<CreateRoleConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CreateRoleConfig _v;
                _v = CreateRoleConfig.DeserializeCreateRoleConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<CharacterType, CreateRoleConfig> DataMap => _dataMap;
        public List<CreateRoleConfig> DataList => _dataList;

        public CreateRoleConfig GetOrDefault(CharacterType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public CreateRoleConfig Get(CharacterType key) => _dataMap[key];
        public CreateRoleConfig this[CharacterType key] => _dataMap[key];

        partial void PostInit();
    }
}
