
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DailyConfig : BeanBase
    {
        public DailyConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ActivityType = (ActivityType)_buf.ReadInt();
            DailyType = (DailyType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Days = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Days.Add(_e0);}}
            StartTime = _buf.ReadLong();
            EndTime = _buf.ReadLong();

            PostInit();
        }

        public static DailyConfig DeserializeDailyConfig(ByteBuf _buf)
        {
            return new DailyConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 活动类型
        /// </summary>
        public readonly ActivityType ActivityType;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly DailyType DailyType;

        /// <summary>
        /// 指定周几
        /// </summary>
        public readonly System.Collections.Generic.List<int> Days;

        /// <summary>
        /// 开启时间
        /// </summary>
        public readonly long StartTime;

        /// <summary>
        /// 结束时间
        /// </summary>
        public readonly long EndTime;

        public const int __ID__ = 958021275;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ActivityType:" + ActivityType + ","
            + "DailyType:" + DailyType + ","
            + "Days:" + Luban.StringUtil.CollectionToString(Days) + ","
            + "StartTime:" + StartTime + ","
            + "EndTime:" + EndTime + ","
            + "}";
        }

        partial void PostInit();
    }
}
