
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DungeonConfig : BeanBase
    {
        public DungeonConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Scene = _buf.ReadInt();
            PreStage = _buf.ReadInt();
            BornPosition = vec3.Deserializevec3(_buf);
            BornRotation = _buf.ReadFloat();
            During = _buf.ReadLong();

            PostInit();
        }

        public static DungeonConfig DeserializeDungeonConfig(ByteBuf _buf)
        {
            return new DungeonConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 地下城场景编号
        /// </summary>
        public readonly int Scene;

        /// <summary>
        /// 地下城场景编号
        /// </summary>
        public SceneConfig SceneConfig => SceneConfigCategory.Instance.GetOrDefault(Scene);

        /// <summary>
        /// 前置地下城编号
        /// </summary>
        public readonly int PreStage;

        /// <summary>
        /// 出生点坐标
        /// </summary>
        public readonly vec3 BornPosition;

        /// <summary>
        /// 出生点旋转
        /// </summary>
        public readonly float BornRotation;

        /// <summary>
        /// 副本时长
        /// </summary>
        public readonly long During;

        public const int __ID__ = -536623492;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Scene:" + Scene + ","
            + "PreStage:" + PreStage + ","
            + "BornPosition:" + BornPosition + ","
            + "BornRotation:" + BornRotation + ","
            + "During:" + During + ","
            + "}";
        }

        partial void PostInit();
    }
}
