
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 地下城配置表
    /// </summary>
    [Config]
    public partial class DungeonConfigCategory : Singleton<DungeonConfigCategory>
    {
        private readonly Dictionary<int, DungeonConfig> _dataMap;
        private readonly List<DungeonConfig> _dataList;

        public DungeonConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, DungeonConfig>();
            _dataList = new List<DungeonConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                DungeonConfig _v;
                _v = DungeonConfig.DeserializeDungeonConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, DungeonConfig> DataMap => _dataMap;
        public List<DungeonConfig> DataList => _dataList;

        public DungeonConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public DungeonConfig Get(int key) => _dataMap[key];
        public DungeonConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
