
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EquipmentHoles : BeanBase
    {
        public EquipmentHoles(ByteBuf _buf)
        {
            HoleColor = (GemColor)_buf.ReadInt();
            PropertyPack = _buf.ReadInt();

            PostInit();
        }

        public static EquipmentHoles DeserializeEquipmentHoles(ByteBuf _buf)
        {
            return new EquipmentHoles(_buf);
        }

        public readonly GemColor HoleColor;

        public readonly int PropertyPack;

        public const int __ID__ = 1086382821;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "HoleColor:" + HoleColor + ","
            + "PropertyPack:" + PropertyPack + ","
            + "}";
        }

        partial void PostInit();
    }
}
