
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 装备配置表
    /// </summary>
    [Config]
    public partial class EquipmentConfigCategory : Singleton<EquipmentConfigCategory>
    {
        private readonly Dictionary<int, EquipmentConfig> _dataMap;
        private readonly List<EquipmentConfig> _dataList;

        public EquipmentConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EquipmentConfig>();
            _dataList = new List<EquipmentConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EquipmentConfig _v;
                _v = EquipmentConfig.DeserializeEquipmentConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EquipmentConfig> DataMap => _dataMap;
        public List<EquipmentConfig> DataList => _dataList;

        public EquipmentConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public EquipmentConfig Get(int key) => _dataMap[key];
        public EquipmentConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
