
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum EquipmentType
    {
        EquipmentType_None = 0,

        /// <summary>
        /// 头部
        /// </summary>
        EquipmentType_Head = 1,

        /// <summary>
        /// 项链
        /// </summary>
        EquipmentType_Necklace = 2,

        /// <summary>
        /// 肩膀
        /// </summary>
        EquipmentType_Shoulder = 3,

        /// <summary>
        /// 胸
        /// </summary>
        EquipmentType_Chest = 4,

        /// <summary>
        /// 腰带
        /// </summary>
        EquipmentType_Belt = 5,

        /// <summary>
        /// 裤子
        /// </summary>
        EquipmentType_Trousers = 6,

        /// <summary>
        /// 鞋子
        /// </summary>
        EquipmentType_Shoes = 7,

        /// <summary>
        /// 戒指
        /// </summary>
        EquipmentType_Ring = 8,

        /// <summary>
        /// 饰品
        /// </summary>
        EquipmentType_Jewelry = 9,

    }
}
