
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GameItemBean : BeanBase
    {
        public GameItemBean(ByteBuf _buf)
        {
            ItemConfig = _buf.ReadInt();
            ItemAmount = _buf.ReadLong();

            PostInit();
        }

        public static GameItemBean DeserializeGameItemBean(ByteBuf _buf)
        {
            return new GameItemBean(_buf);
        }

        public readonly int ItemConfig;

        public ItemConfig ItemConfigConfig => ItemConfigCategory.Instance.GetOrDefault(ItemConfig);

        public readonly long ItemAmount;

        public const int __ID__ = 1496527765;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "ItemConfig:" + ItemConfig + ","
            + "ItemAmount:" + ItemAmount + ","
            + "}";
        }

        partial void PostInit();
    }
}
