
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum GamePropertyType
    {
        /// <summary>
        /// 等级
        /// </summary>
        GP_Level = 1001,

        /// <summary>
        /// 经验值
        /// </summary>
        GP_Exp = 1002,

        /// <summary>
        /// 最大经验值
        /// </summary>
        GP_MaxExp = 1003,

        /// <summary>
        /// 视野范围
        /// </summary>
        GP_AOI = 1005,

        /// <summary>
        /// 沉默
        /// </summary>
        GP_Silent = 1006,

        /// <summary>
        /// 禁止移动
        /// </summary>
        GP_CantMove = 1007,

        /// <summary>
        /// 禁止转向
        /// </summary>
        GP_CantRotate = 1008,

        /// <summary>
        /// 禁止选择
        /// </summary>
        GP_CantBeSelected = 1009,

        /// <summary>
        /// 护盾
        /// </summary>
        GP_Shield = 1010,

        /// <summary>
        /// 施法速度
        /// </summary>
        GP_CastSpeed = 1011,

        /// <summary>
        /// 生命值
        /// </summary>
        GP_Hp = 1101,

        /// <summary>
        /// 最大生命值
        /// </summary>
        GP_MaxHp = 1102,

        /// <summary>
        /// 魔法值
        /// </summary>
        GP_Mp = 1103,

        /// <summary>
        /// 最大魔法值
        /// </summary>
        GP_MaxMp = 1104,

        /// <summary>
        /// 移动速度
        /// </summary>
        GP_Speed = 1004,

        /// <summary>
        /// 移动速度基础值
        /// </summary>
        GP_SpeedBase = 10041,

        /// <summary>
        /// 移动速度附加值
        /// </summary>
        GP_SpeedAdd = 10042,

        /// <summary>
        /// 移动速度百分比
        /// </summary>
        GP_SpeedPct = 10043,

        /// <summary>
        /// 移动速度最终附加值
        /// </summary>
        GP_SpeedFinalAdd = 10044,

        /// <summary>
        /// 移动速度最终百分比
        /// </summary>
        GP_SpeedFinalPct = 10045,

        /// <summary>
        /// 攻击
        /// </summary>
        GP_Atk = 1105,

        /// <summary>
        /// 攻击基础值
        /// </summary>
        GP_AtkBase = 11051,

        /// <summary>
        /// 攻击附加值
        /// </summary>
        GP_AtkAdd = 11052,

        /// <summary>
        /// 攻击百分比
        /// </summary>
        GP_AtkPct = 11053,

        /// <summary>
        /// 攻击最终附加值
        /// </summary>
        GP_AtkFinalAdd = 11054,

        /// <summary>
        /// 攻击最终百分比
        /// </summary>
        GP_AtkFinalPct = 11055,

        /// <summary>
        /// 防御
        /// </summary>
        GP_Def = 1106,

        /// <summary>
        /// 防御基础值
        /// </summary>
        GP_DefBase = 11061,

        /// <summary>
        /// 防御附加值
        /// </summary>
        GP_DefAdd = 11062,

        /// <summary>
        /// 防御百分比
        /// </summary>
        GP_DefPct = 11063,

        /// <summary>
        /// 防御最终附加值
        /// </summary>
        GP_DefFinalAdd = 11064,

        /// <summary>
        /// 防御最终百分比
        /// </summary>
        GP_DefFinalPct = 11065,

        /// <summary>
        /// 命中
        /// </summary>
        GP_Hit = 1107,

        /// <summary>
        /// 命中基础值
        /// </summary>
        GP_HitBase = 11071,

        /// <summary>
        /// 命中附加值
        /// </summary>
        GP_HitAdd = 11072,

        /// <summary>
        /// 命中百分比
        /// </summary>
        GP_HitPct = 11073,

        /// <summary>
        /// 命中最终附加值
        /// </summary>
        GP_HitFinalAdd = 11074,

        /// <summary>
        /// 命中最终百分比
        /// </summary>
        GP_HitFinalPct = 11075,

        /// <summary>
        /// 暴击
        /// </summary>
        GP_Crit = 1108,

        /// <summary>
        /// 暴击基础值
        /// </summary>
        GP_CritBase = 11081,

        /// <summary>
        /// 暴击附加值
        /// </summary>
        GP_CritAdd = 11082,

        /// <summary>
        /// 暴击百分比
        /// </summary>
        GP_CritPct = 11083,

        /// <summary>
        /// 暴击最终附加值
        /// </summary>
        GP_CritFinalAdd = 11084,

        /// <summary>
        /// 暴击最终百分比
        /// </summary>
        GP_CritFinalPct = 11085,

        /// <summary>
        /// 战场速度
        /// </summary>
        GP_BattleSpeed = 1109,

        /// <summary>
        /// 战场速度基础值
        /// </summary>
        GP_BattleSpeedBase = 11091,

        /// <summary>
        /// 战场速度附加值
        /// </summary>
        GP_BattleSpeedAdd = 11092,

        /// <summary>
        /// 战场速度百分比
        /// </summary>
        GP_BattleSpeedPct = 11093,

        /// <summary>
        /// 战场速度最终附加值
        /// </summary>
        GP_BattleSpeedFinalAdd = 11094,

        /// <summary>
        /// 战场速度最终百分比
        /// </summary>
        GP_BattleSpeedFinalPct = 11095,

    }
}
