
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum GameItemUseType
    {
        /// <summary>
        /// 获得货币
        /// </summary>
        GameItemUseType_Currency = 1,

        /// <summary>
        /// 接取任务
        /// </summary>
        GameItemUseType_Task = 2,

        /// <summary>
        /// 获得增益
        /// </summary>
        GameItemUseType_Buff = 3,

    }
}
