
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GemConfig : BeanBase
    {
        public GemConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ColorFlag = (GemColor)_buf.ReadInt();
            Property = _buf.ReadInt();

            PostInit();
        }

        public static GemConfig DeserializeGemConfig(ByteBuf _buf)
        {
            return new GemConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 宝石颜色
        /// </summary>
        public readonly GemColor ColorFlag;

        /// <summary>
        /// 宝石属性
        /// </summary>
        public readonly int Property;

        /// <summary>
        /// 宝石属性
        /// </summary>
        public PropertyConfig PropertyConfig => PropertyConfigCategory.Instance.GetOrDefault(Property);

        public const int __ID__ = 427632465;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ColorFlag:" + ColorFlag + ","
            + "Property:" + Property + ","
            + "}";
        }

        partial void PostInit();
    }
}
