
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GlobalDataConfig : BeanBase
    {
        public GlobalDataConfig(ByteBuf _buf)
        {
            BagCapacity = _buf.ReadInt();
            BagMaxCapacity = _buf.ReadInt();
            CameraMinDistance = _buf.ReadFloat();
            CameraMaxDistance = _buf.ReadFloat();
            CreateRoleMaxLimit = _buf.ReadInt();

            PostInit();
        }

        public static GlobalDataConfig DeserializeGlobalDataConfig(ByteBuf _buf)
        {
            return new GlobalDataConfig(_buf);
        }

        /// <summary>
        /// 背包初始容量
        /// </summary>
        public readonly int BagCapacity;

        /// <summary>
        /// 背包最大容量
        /// </summary>
        public readonly int BagMaxCapacity;

        /// <summary>
        /// 相机最近距离
        /// </summary>
        public readonly float CameraMinDistance;

        /// <summary>
        /// 相机最远距离
        /// </summary>
        public readonly float CameraMaxDistance;

        /// <summary>
        /// 创角数量限制
        /// </summary>
        public readonly int CreateRoleMaxLimit;

        public const int __ID__ = 394046383;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "BagCapacity:" + BagCapacity + ","
            + "BagMaxCapacity:" + BagMaxCapacity + ","
            + "CameraMinDistance:" + CameraMinDistance + ","
            + "CameraMaxDistance:" + CameraMaxDistance + ","
            + "CreateRoleMaxLimit:" + CreateRoleMaxLimit + ","
            + "}";
        }

        partial void PostInit();
    }
}
