
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class HitFlyParams : ActionParam
    {
        public HitFlyParams(ByteBuf _buf) : base(_buf) 
        {
            Range = _buf.ReadInt();
            Direction = _buf.ReadInt();
            BuffConfigId = _buf.ReadInt();

            PostInit();
        }

        public static HitFlyParams DeserializeHitFlyParams(ByteBuf _buf)
        {
            return new HitFlyParams(_buf);
        }

        public readonly int Range;

        public readonly int Direction;

        public readonly int BuffConfigId;

        public BuffConfig BuffConfigIdConfig => BuffConfigCategory.Instance.GetOrDefault(BuffConfigId);

        public const int __ID__ = -643676762;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Range:" + Range + ","
            + "Direction:" + Direction + ","
            + "BuffConfigId:" + BuffConfigId + ","
            + "}";
        }

        partial void PostInit();
    }
}
