
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ItemPackConfig : BeanBase
    {
        public ItemPackConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            PackType = (PackType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Items = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     Items.Add(_k0, _v0);}}

            PostInit();
        }

        public static ItemPackConfig DeserializeItemPackConfig(ByteBuf _buf)
        {
            return new ItemPackConfig(_buf);
        }

        /// <summary>
        /// 礼包编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 礼包编号
        /// </summary>
        public ItemConfig IdConfig => ItemConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 礼包类型
        /// </summary>
        public readonly PackType PackType;

        /// <summary>
        /// 礼包内道具
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> Items;

        public const int __ID__ = 803783246;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PackType:" + PackType + ","
            + "Items:" + Luban.StringUtil.CollectionToString(Items) + ","
            + "}";
        }

        partial void PostInit();
    }
}
