
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 道具配置表
    /// </summary>
    [Config]
    public partial class ItemConfigCategory : Singleton<ItemConfigCategory>
    {
        private readonly Dictionary<int, ItemConfig> _dataMap;
        private readonly List<ItemConfig> _dataList;

        public ItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ItemConfig>();
            _dataList = new List<ItemConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ItemConfig _v;
                _v = ItemConfig.DeserializeItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ItemConfig> DataMap => _dataMap;
        public List<ItemConfig> DataList => _dataList;

        public ItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ItemConfig Get(int key) => _dataMap[key];
        public ItemConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
