
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 道具礼包表
    /// </summary>
    [Config]
    public partial class ItemPackConfigCategory : Singleton<ItemPackConfigCategory>
    {
        private readonly Dictionary<int, ItemPackConfig> _dataMap;
        private readonly List<ItemPackConfig> _dataList;

        public ItemPackConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ItemPackConfig>();
            _dataList = new List<ItemPackConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ItemPackConfig _v;
                _v = ItemPackConfig.DeserializeItemPackConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ItemPackConfig> DataMap => _dataMap;
        public List<ItemPackConfig> DataList => _dataList;

        public ItemPackConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ItemPackConfig Get(int key) => _dataMap[key];
        public ItemPackConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
