
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ItemUseConfig : BeanBase
    {
        public ItemUseConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            GameItemUseType = (GameItemUseType)_buf.ReadInt();
            GameItemUseParam = GameItemUseParam.DeserializeGameItemUseParam(_buf);

            PostInit();
        }

        public static ItemUseConfig DeserializeItemUseConfig(ByteBuf _buf)
        {
            return new ItemUseConfig(_buf);
        }

        /// <summary>
        /// 道具编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 道具编号
        /// </summary>
        public ItemConfig IdConfig => ItemConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 道具使用类型
        /// </summary>
        public readonly GameItemUseType GameItemUseType;

        public readonly GameItemUseParam GameItemUseParam;

        public const int __ID__ = 2109033910;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "GameItemUseType:" + GameItemUseType + ","
            + "GameItemUseParam:" + GameItemUseParam + ","
            + "}";
        }

        partial void PostInit();
    }
}
