
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MinMax : BeanBase
    {
        public MinMax(ByteBuf _buf)
        {
            Min = _buf.ReadLong();
            Max = _buf.ReadLong();

            PostInit();
        }

        public static MinMax DeserializeMinMax(ByteBuf _buf)
        {
            return new MinMax(_buf);
        }

        public readonly long Min;

        public readonly long Max;

        public const int __ID__ = -1990198830;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Min:" + Min + ","
            + "Max:" + Max + ","
            + "}";
        }

        partial void PostInit();
    }
}
