
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ModifyPropertyActionParams : ActionParam
    {
        public ModifyPropertyActionParams(ByteBuf _buf) : base(_buf) 
        {
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ModifyProperties = new System.Collections.Generic.List<Properties>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Properties _e0;  _e0 = Properties.DeserializeProperties(_buf); ModifyProperties.Add(_e0);}}

            PostInit();
        }

        public static ModifyPropertyActionParams DeserializeModifyPropertyActionParams(ByteBuf _buf)
        {
            return new ModifyPropertyActionParams(_buf);
        }

        public readonly System.Collections.Generic.List<Properties> ModifyProperties;

        public const int __ID__ = 1041245643;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "ModifyProperties:" + Luban.StringUtil.CollectionToString(ModifyProperties) + ","
            + "}";
        }

        partial void PostInit();
    }
}
