
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum NpcType
    {
        /// <summary>
        /// 普通Npc
        /// </summary>
        NpcType_Normal = 1,

    }
}
