
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 属性随机表
    /// </summary>
    [Config]
    public partial class PropertyRandomConfigCategory : Singleton<PropertyRandomConfigCategory>
    {
        private readonly Dictionary<int, PropertyRandomConfig> _dataMap;
        private readonly List<PropertyRandomConfig> _dataList;

        public PropertyRandomConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PropertyRandomConfig>();
            _dataList = new List<PropertyRandomConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PropertyRandomConfig _v;
                _v = PropertyRandomConfig.DeserializePropertyRandomConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PropertyRandomConfig> DataMap => _dataMap;
        public List<PropertyRandomConfig> DataList => _dataList;

        public PropertyRandomConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public PropertyRandomConfig Get(int key) => _dataMap[key];
        public PropertyRandomConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
