
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PropertyScoreConfig : BeanBase
    {
        public PropertyScoreConfig(ByteBuf _buf)
        {
            Id = (GamePropertyType)_buf.ReadInt();
            Score = _buf.ReadInt();

            PostInit();
        }

        public static PropertyScoreConfig DeserializePropertyScoreConfig(ByteBuf _buf)
        {
            return new PropertyScoreConfig(_buf);
        }

        /// <summary>
        /// 属性包id
        /// </summary>
        public readonly GamePropertyType Id;

        /// <summary>
        /// 战斗力分数
        /// </summary>
        public readonly int Score;

        public const int __ID__ = -665779393;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Score:" + Score + ","
            + "}";
        }

        partial void PostInit();
    }
}
