
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum RaceType
    {
        /// <summary>
        /// 人类
        /// </summary>
        RaceType_Human = 1,

        /// <summary>
        /// 暗夜精灵
        /// </summary>
        RaceType_NightElf = 2,

        /// <summary>
        /// 矮人
        /// </summary>
        RaceType_Dwarf = 4,

        /// <summary>
        /// 德莱尼
        /// </summary>
        RaceType_Draenei = 8,

        /// <summary>
        /// 兽人
        /// </summary>
        RaceType_Orc = 16,

        /// <summary>
        /// 巨魔
        /// </summary>
        RaceType_Troll = 32,

        /// <summary>
        /// 亡灵
        /// </summary>
        RaceType_Undead = 64,

        /// <summary>
        /// 牛头人
        /// </summary>
        RaceType_Tauren = 128,

        /// <summary>
        /// 血精灵
        /// </summary>
        RaceType_BloodElf = 256,

        /// <summary>
        /// 侏儒
        /// </summary>
        RaceType_Gnome = 512,

    }
}
