
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ReliveParams : ActionParam
    {
        public ReliveParams(ByteBuf _buf) : base(_buf) 
        {
            Hp = _buf.ReadInt();
            Mp = _buf.ReadInt();

            PostInit();
        }

        public static ReliveParams DeserializeReliveParams(ByteBuf _buf)
        {
            return new ReliveParams(_buf);
        }

        public readonly int Hp;

        public readonly int Mp;

        public const int __ID__ = 1658762277;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Hp:" + Hp + ","
            + "Mp:" + Mp + ","
            + "}";
        }

        partial void PostInit();
    }
}
