
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 场景怪物配置
    /// </summary>
    [Config]
    public partial class SceneMonsterConfigCategory : Singleton<SceneMonsterConfigCategory>
    {
        private readonly Dictionary<int, SceneMonsterConfig> _dataMap;
        private readonly List<SceneMonsterConfig> _dataList;

        public SceneMonsterConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SceneMonsterConfig>();
            _dataList = new List<SceneMonsterConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SceneMonsterConfig _v;
                _v = SceneMonsterConfig.DeserializeSceneMonsterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SceneMonsterConfig> DataMap => _dataMap;
        public List<SceneMonsterConfig> DataList => _dataList;

        public SceneMonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SceneMonsterConfig Get(int key) => _dataMap[key];
        public SceneMonsterConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
