
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class SelectTargetsParams : BeanBase
    {
        public SelectTargetsParams(ByteBuf _buf)
        {

            PostInit();
        }

        public static SelectTargetsParams DeserializeSelectTargetsParams(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case Single.__ID__: return new Single(_buf);
                case Cycle.__ID__: return new Cycle(_buf);
                case ForwardRect.__ID__: return new ForwardRect(_buf);
                case ForwardSector180.__ID__: return new ForwardSector180(_buf);
                case SelectCycle.__ID__: return new SelectCycle(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
