
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum SelectTargetType
    {
        /// <summary>
        /// 单体
        /// </summary>
        SelectTargetType_SelectSingle = 1,

        /// <summary>
        /// 自身圆形范围
        /// </summary>
        SelectTargetType_AroundCycle = 2,

        /// <summary>
        /// 前方矩形范围
        /// </summary>
        SelectTargetType_ForwardRect = 3,

        /// <summary>
        /// 指定圆形范围
        /// </summary>
        SelectTargetType_SelectCycle = 4,

    }
}
