
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SevenDayConfig : BeanBase
    {
        public SevenDayConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Reward = _buf.ReadInt();

            PostInit();
        }

        public static SevenDayConfig DeserializeSevenDayConfig(ByteBuf _buf)
        {
            return new SevenDayConfig(_buf);
        }

        /// <summary>
        /// 天数
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 奖励
        /// </summary>
        public readonly int Reward;

        /// <summary>
        /// 奖励
        /// </summary>
        public RewardConfig RewardConfig => RewardConfigCategory.Instance.GetOrDefault(Reward);

        public const int __ID__ = -834979695;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Reward:" + Reward + ","
            + "}";
        }

        partial void PostInit();
    }
}
