
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 商店配置
    /// </summary>
    [Config]
    public partial class ShopConfigCategory : Singleton<ShopConfigCategory>
    {
        private readonly Dictionary<int, ShopConfig> _dataMap;
        private readonly List<ShopConfig> _dataList;

        public ShopConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ShopConfig>();
            _dataList = new List<ShopConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ShopConfig _v;
                _v = ShopConfig.DeserializeShopConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ShopConfig> DataMap => _dataMap;
        public List<ShopConfig> DataList => _dataList;

        public ShopConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ShopConfig Get(int key) => _dataMap[key];
        public ShopConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
