
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 签到配置
    /// </summary>
    [Config]
    public partial class SignConfigCategory : Singleton<SignConfigCategory>
    {
        private readonly Dictionary<int, SignConfig> _dataMap;
        private readonly List<SignConfig> _dataList;

        public SignConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SignConfig>();
            _dataList = new List<SignConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SignConfig _v;
                _v = SignConfig.DeserializeSignConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SignConfig> DataMap => _dataMap;
        public List<SignConfig> DataList => _dataList;

        public SignConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SignConfig Get(int key) => _dataMap[key];
        public SignConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
