
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class Single : SelectTargetsParams
    {
        public Single(ByteBuf _buf) : base(_buf) 
        {
            IncludeSelf = _buf.ReadBool();

            PostInit();
        }

        public static Single DeserializeSingle(ByteBuf _buf)
        {
            return new Single(_buf);
        }

        public readonly bool IncludeSelf;

        public const int __ID__ = -1818398616;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "IncludeSelf:" + IncludeSelf + ","
            + "}";
        }

        partial void PostInit();
    }
}
