
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulLevelConfig : BeanBase
    {
        public SoulLevelConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Level = _buf.ReadInt();
            CurrencyType = (CurrencyType)_buf.ReadInt();
            CurrencyValue = _buf.ReadLong();
            if(_buf.ReadBool()){ BreakItem = _buf.ReadInt(); } else { BreakItem = null; }
            if(_buf.ReadBool()){ BreakItemAmount = _buf.ReadLong(); } else { BreakItemAmount = null; }
            PropertyPack = _buf.ReadInt();

            PostInit();
        }

        public static SoulLevelConfig DeserializeSoulLevelConfig(ByteBuf _buf)
        {
            return new SoulLevelConfig(_buf);
        }

        /// <summary>
        /// 灵编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;

        /// <summary>
        /// 升级货币
        /// </summary>
        public readonly CurrencyType CurrencyType;

        /// <summary>
        /// 升级货币值
        /// </summary>
        public readonly long CurrencyValue;

        /// <summary>
        /// 突破道具编号
        /// </summary>
        public readonly int? BreakItem;

        /// <summary>
        /// 突破道具个数
        /// </summary>
        public readonly long? BreakItemAmount;

        /// <summary>
        /// 等级属性包
        /// </summary>
        public readonly int PropertyPack;

        /// <summary>
        /// 等级属性包
        /// </summary>
        public PropertyConfig PropertyPackConfig => PropertyConfigCategory.Instance.GetOrDefault(PropertyPack);

        public const int __ID__ = 69704659;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "CurrencyType:" + CurrencyType + ","
            + "CurrencyValue:" + CurrencyValue + ","
            + "BreakItem:" + BreakItem + ","
            + "BreakItemAmount:" + BreakItemAmount + ","
            + "PropertyPack:" + PropertyPack + ","
            + "}";
        }

        partial void PostInit();
    }
}
