
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulStarConfig : BeanBase
    {
        public SoulStarConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Star = _buf.ReadInt();
            PropertyPack = _buf.ReadInt();

            PostInit();
        }

        public static SoulStarConfig DeserializeSoulStarConfig(ByteBuf _buf)
        {
            return new SoulStarConfig(_buf);
        }

        /// <summary>
        /// 灵编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 灵编号
        /// </summary>
        public SoulConfig IdConfig => SoulConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 星级
        /// </summary>
        public readonly int Star;

        /// <summary>
        /// 星级属性包
        /// </summary>
        public readonly int PropertyPack;

        /// <summary>
        /// 星级属性包
        /// </summary>
        public PropertyConfig PropertyPackConfig => PropertyConfigCategory.Instance.GetOrDefault(PropertyPack);

        public const int __ID__ = -1062012249;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Star:" + Star + ","
            + "PropertyPack:" + PropertyPack + ","
            + "}";
        }

        partial void PostInit();
    }
}
