
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulCastConfig : BeanBase
    {
        public SoulCastConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            TotalTime = _buf.ReadLong();
            CastCooldown = _buf.ReadInt();
            SelectTargetType = (SelectTargetType)_buf.ReadInt();
            CastTargetType = (CastTargetType)_buf.ReadInt();

            PostInit();
        }

        public static SoulCastConfig DeserializeSoulCastConfig(ByteBuf _buf)
        {
            return new SoulCastConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能总时长
        /// </summary>
        public readonly long TotalTime;

        /// <summary>
        /// 技能释放CD
        /// </summary>
        public readonly int CastCooldown;

        /// <summary>
        /// 技能选择目标类型
        /// </summary>
        public readonly SelectTargetType SelectTargetType;

        /// <summary>
        /// 技能释放阵营
        /// </summary>
        public readonly CastTargetType CastTargetType;

        public const int __ID__ = 849955284;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TotalTime:" + TotalTime + ","
            + "CastCooldown:" + CastCooldown + ","
            + "SelectTargetType:" + SelectTargetType + ","
            + "CastTargetType:" + CastTargetType + ","
            + "}";
        }

        partial void PostInit();
    }
}
