
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵信息配置
    /// </summary>
    [Config]
    public partial class SoulConfigCategory : Singleton<SoulConfigCategory>
    {
        private readonly Dictionary<int, SoulConfig> _dataMap;
        private readonly List<SoulConfig> _dataList;

        public SoulConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulConfig>();
            _dataList = new List<SoulConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulConfig _v;
                _v = SoulConfig.DeserializeSoulConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulConfig> DataMap => _dataMap;
        public List<SoulConfig> DataList => _dataList;

        public SoulConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulConfig Get(int key) => _dataMap[key];
        public SoulConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
