
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulTalentActionConfig : BeanBase
    {
        public SoulTalentActionConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Action = _buf.ReadInt();

            PostInit();
        }

        public static SoulTalentActionConfig DeserializeSoulTalentActionConfig(ByteBuf _buf)
        {
            return new SoulTalentActionConfig(_buf);
        }

        /// <summary>
        /// 灵天赋行为编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 行为编号
        /// </summary>
        public readonly int Action;

        /// <summary>
        /// 行为编号
        /// </summary>
        public ActionConfig ActionConfig => ActionConfigCategory.Instance.GetOrDefault(Action);

        public const int __ID__ = -895428713;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Action:" + Action + ","
            + "}";
        }

        partial void PostInit();
    }
}
