
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum SoulActionType
    {
        /// <summary>
        /// 灵修改属性行为
        /// </summary>
        SoulActionType_ModifyProperty = 1,

        /// <summary>
        /// 灵伤害行为
        /// </summary>
        SoulActionType_Damage = 2,

    }
}
