
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SubTaskConfig : BeanBase
    {
        public SubTaskConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            SubTaskType = (SubTaskType)_buf.ReadInt();

            PostInit();
        }

        public static SubTaskConfig DeserializeSubTaskConfig(ByteBuf _buf)
        {
            return new SubTaskConfig(_buf);
        }

        /// <summary>
        /// 任务id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 任务名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 子任务类型
        /// </summary>
        public readonly SubTaskType SubTaskType;

        public const int __ID__ = 1833281383;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "SubTaskType:" + SubTaskType + ","
            + "}";
        }

        partial void PostInit();
    }
}
