
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 系统提示配置表
    /// </summary>
    [Config]
    public partial class SystemInfoConfigCategory : Singleton<SystemInfoConfigCategory>
    {
        private readonly Dictionary<int, SystemInfoConfig> _dataMap;
        private readonly List<SystemInfoConfig> _dataList;

        public SystemInfoConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SystemInfoConfig>();
            _dataList = new List<SystemInfoConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SystemInfoConfig _v;
                _v = SystemInfoConfig.DeserializeSystemInfoConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SystemInfoConfig> DataMap => _dataMap;
        public List<SystemInfoConfig> DataList => _dataList;

        public SystemInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SystemInfoConfig Get(int key) => _dataMap[key];
        public SystemInfoConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
