
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum TaskType
    {
        /// <summary>
        /// 主线任务
        /// </summary>
        TaskType_Main = 1,

        /// <summary>
        /// 支线任务
        /// </summary>
        TaskType_Branch = 2,

        /// <summary>
        /// 子任务
        /// </summary>
        TaskType_Sub = 3,

        /// <summary>
        /// 日常任务
        /// </summary>
        TaskType_Daily = 4,

        /// <summary>
        /// 周常任务
        /// </summary>
        TaskType_Weeky = 5,

    }
}
