
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TaskConfig : BeanBase
    {
        public TaskConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Type = (TaskType)_buf.ReadInt();
            SubTask = _buf.ReadString();
            PreTask = _buf.ReadInt();
            NextTask = _buf.ReadInt();

            PostInit();
        }

        public static TaskConfig DeserializeTaskConfig(ByteBuf _buf)
        {
            return new TaskConfig(_buf);
        }

        /// <summary>
        /// 任务id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 任务名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 任务类型
        /// </summary>
        public readonly TaskType Type;

        /// <summary>
        /// 子任务列表
        /// </summary>
        public readonly string SubTask;

        /// <summary>
        /// 前置任务
        /// </summary>
        public readonly int PreTask;

        /// <summary>
        /// 后置任务
        /// </summary>
        public readonly int NextTask;

        public const int __ID__ = -1794275001;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "SubTask:" + SubTask + ","
            + "PreTask:" + PreTask + ","
            + "NextTask:" + NextTask + ","
            + "}";
        }

        partial void PostInit();
    }
}
