
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 任务配置表
    /// </summary>
    [Config]
    public partial class TaskConfigCategory : Singleton<TaskConfigCategory>
    {
        private readonly Dictionary<int, TaskConfig> _dataMap;
        private readonly List<TaskConfig> _dataList;

        public TaskConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TaskConfig>();
            _dataList = new List<TaskConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TaskConfig _v;
                _v = TaskConfig.DeserializeTaskConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TaskConfig> DataMap => _dataMap;
        public List<TaskConfig> DataList => _dataList;

        public TaskConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public TaskConfig Get(int key) => _dataMap[key];
        public TaskConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
