
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TauntParams : ActionParam
    {
        public TauntParams(ByteBuf _buf) : base(_buf) 
        {
            Hatred = _buf.ReadInt();

            PostInit();
        }

        public static TauntParams DeserializeTauntParams(ByteBuf _buf)
        {
            return new TauntParams(_buf);
        }

        public readonly int Hatred;

        public const int __ID__ = 1464419956;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Hatred:" + Hatred + ","
            + "}";
        }

        partial void PostInit();
    }
}
