
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TreatmentParams : ActionParam
    {
        public TreatmentParams(ByteBuf _buf) : base(_buf) 
        {
            TreatValue = _buf.ReadInt();

            PostInit();
        }

        public static TreatmentParams DeserializeTreatmentParams(ByteBuf _buf)
        {
            return new TreatmentParams(_buf);
        }

        public readonly int TreatValue;

        public const int __ID__ = 936238078;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "TreatValue:" + TreatValue + ","
            + "}";
        }

        partial void PostInit();
    }
}
