
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UIGroupType
    {
        /// <summary>
        /// 基础类型（用于以场景，玩法类基础的类型组）
        /// </summary>
        Base = 1,

        /// <summary>
        /// 基础类型 基础上附加
        /// </summary>
        BaseFixed = 2,

        /// <summary>
        /// 常规组类型
        /// </summary>
        Normal = 3,

        /// <summary>
        /// 追加类型（组的基础上追加另一个组）
        /// </summary>
        NormalFixed = 4,

        /// <summary>
        /// 通用base
        /// </summary>
        GeneralBase = 99,

    }
}
