
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class UIGroupConfig : BeanBase
    {
        public UIGroupConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = (UIGroupType)_buf.ReadInt();
            Vague = _buf.ReadBool();
            OpenDelay = _buf.ReadBool();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Conditions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Conditions.Add(_e0);}}
            TraceId = _buf.ReadInt();

            PostInit();
        }

        public static UIGroupConfig DeserializeUIGroupConfig(ByteBuf _buf)
        {
            return new UIGroupConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 组类型
        /// </summary>
        public readonly UIGroupType Type;

        /// <summary>
        /// 背景是否模糊
        /// </summary>
        public readonly bool Vague;

        /// <summary>
        /// 黑幕过度
        /// </summary>
        public readonly bool OpenDelay;

        /// <summary>
        /// 界面打开条件
        /// </summary>
        public readonly System.Collections.Generic.List<int> Conditions;

        /// <summary>
        /// 追溯Id
        /// </summary>
        public readonly int TraceId;

        public const int __ID__ = -666942611;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Vague:" + Vague + ","
            + "OpenDelay:" + OpenDelay + ","
            + "Conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
            + "TraceId:" + TraceId + ","
            + "}";
        }

        partial void PostInit();
    }
}
