
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// UI配置表
    /// </summary>
    [Config]
    public partial class UIGroupSubConfigCategory : Singleton<UIGroupSubConfigCategory>
    {
        private readonly Dictionary<int, UIGroupSubConfig> _dataMap;
        private readonly List<UIGroupSubConfig> _dataList;

        public UIGroupSubConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, UIGroupSubConfig>();
            _dataList = new List<UIGroupSubConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                UIGroupSubConfig _v;
                _v = UIGroupSubConfig.DeserializeUIGroupSubConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, UIGroupSubConfig> DataMap => _dataMap;
        public List<UIGroupSubConfig> DataList => _dataList;

        public UIGroupSubConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public UIGroupSubConfig Get(int key) => _dataMap[key];
        public UIGroupSubConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
