
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum AchievementType
    {
        /// <summary>
        /// 属性比较
        /// </summary>
        AchievementType_PropertyCompare = 1,

        /// <summary>
        /// 货币比较
        /// </summary>
        AchievementType_Currency = 2,

    }
}
