
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ActivityType
    {
        /// <summary>
        /// 签到
        /// </summary>
        ActivityType_Signin = 1,

        /// <summary>
        /// 每日礼包1
        /// </summary>
        ActivityType_DailyGift1 = 2,

        /// <summary>
        /// 每周礼包1
        /// </summary>
        ActivityType_WeekyGift1 = 3,

        /// <summary>
        /// 世界boss1
        /// </summary>
        ActivityType_WorldBoss1 = 4,

    }
}
