
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum ActionType
    {
        /// <summary>
        /// 修改属性行为
        /// </summary>
        ActionType_ModifyProperty = 1,

        /// <summary>
        /// 伤害行为
        /// </summary>
        ActionType_Damage = 2,

    }
}
