
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class AIParam : BeanBase
    {
        public AIParam(ByteBuf _buf)
        {

            PostInit();
        }

        public static AIParam DeserializeAIParam(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case AIPatrolParam.__ID__: return new AIPatrolParam(_buf);
                case AICastParam.__ID__: return new AICastParam(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
