
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AIPatrolParam : AIParam
    {
        public AIPatrolParam(ByteBuf _buf) : base(_buf) 
        {
            StayTimeMin = _buf.ReadInt();
            StayTimeMax = _buf.ReadInt();

            PostInit();
        }

        public static AIPatrolParam DeserializeAIPatrolParam(ByteBuf _buf)
        {
            return new AIPatrolParam(_buf);
        }

        public readonly int StayTimeMin;

        public readonly int StayTimeMax;

        public const int __ID__ = -164295591;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "StayTimeMin:" + StayTimeMin + ","
            + "StayTimeMax:" + StayTimeMax + ","
            + "}";
        }

        partial void PostInit();
    }
}
