
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AvocationConfig : BeanBase
    {
        public AvocationConfig(ByteBuf _buf)
        {
            Type = (AvocationType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpgradeConsume = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     UpgradeConsume.Add(_k0, _v0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpgradeExp = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     UpgradeExp.Add(_k0, _v0);}}

            PostInit();
        }

        public static AvocationConfig DeserializeAvocationConfig(ByteBuf _buf)
        {
            return new AvocationConfig(_buf);
        }

        /// <summary>
        /// 副业类型
        /// </summary>
        public readonly AvocationType Type;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> UpgradeConsume;

        /// <summary>
        /// 升级经验值
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> UpgradeExp;

        public const int __ID__ = 2074643982;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Type:" + Type + ","
            + "UpgradeConsume:" + Luban.StringUtil.CollectionToString(UpgradeConsume) + ","
            + "UpgradeExp:" + Luban.StringUtil.CollectionToString(UpgradeExp) + ","
            + "}";
        }

        partial void PostInit();
    }
}
