
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 副业配置表
    /// </summary>
    [Config]
    public partial class AvocationConfigCategory : Singleton<AvocationConfigCategory>
    {
        private readonly Dictionary<AvocationType, AvocationConfig> _dataMap;
        private readonly List<AvocationConfig> _dataList;

        public AvocationConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<AvocationType, AvocationConfig>();
            _dataList = new List<AvocationConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AvocationConfig _v;
                _v = AvocationConfig.DeserializeAvocationConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Type, _v);
            }

            PostInit();
        }

        public Dictionary<AvocationType, AvocationConfig> DataMap => _dataMap;
        public List<AvocationConfig> DataList => _dataList;

        public AvocationConfig GetOrDefault(AvocationType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public AvocationConfig Get(AvocationType key) => _dataMap[key];
        public AvocationConfig this[AvocationType key] => _dataMap[key];

        partial void PostInit();
    }
}
