
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BattlePVEConfig : BeanBase
    {
        public BattlePVEConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Monsters = new System.Collections.Generic.Dictionary<int, BattlePosition>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); BattlePosition _v0;  _v0 = (BattlePosition)_buf.ReadInt();     Monsters.Add(_k0, _v0);}}

            PostInit();
        }

        public static BattlePVEConfig DeserializeBattlePVEConfig(ByteBuf _buf)
        {
            return new BattlePVEConfig(_buf);
        }

        /// <summary>
        /// PVE编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 怪物编号及站位
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, BattlePosition> Monsters;

        public const int __ID__ = 1990713673;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Monsters:" + Luban.StringUtil.CollectionToString(Monsters) + ","
            + "}";
        }

        partial void PostInit();
    }
}
