
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// PVE战斗配置
    /// </summary>
    [Config]
    public partial class BattlePVEConfigCategory : Singleton<BattlePVEConfigCategory>
    {
        private readonly Dictionary<int, BattlePVEConfig> _dataMap;
        private readonly List<BattlePVEConfig> _dataList;

        public BattlePVEConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BattlePVEConfig>();
            _dataList = new List<BattlePVEConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BattlePVEConfig _v;
                _v = BattlePVEConfig.DeserializeBattlePVEConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BattlePVEConfig> DataMap => _dataMap;
        public List<BattlePVEConfig> DataList => _dataList;

        public BattlePVEConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BattlePVEConfig Get(int key) => _dataMap[key];
        public BattlePVEConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
