
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BornSceneConfig : BeanBase
    {
        public BornSceneConfig(ByteBuf _buf)
        {
            Id = (RaceType)_buf.ReadInt();
            BornScene = _buf.ReadString();

            PostInit();
        }

        public static BornSceneConfig DeserializeBornSceneConfig(ByteBuf _buf)
        {
            return new BornSceneConfig(_buf);
        }

        /// <summary>
        /// 种族
        /// </summary>
        public readonly RaceType Id;

        /// <summary>
        /// 初始场景
        /// </summary>
        public readonly string BornScene;

        public const int __ID__ = -701408315;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BornScene:" + BornScene + ","
            + "}";
        }

        partial void PostInit();
    }
}
