
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 客户端Buff配置
    /// </summary>
    [Config]
    public partial class BuffClientConfigCategory : Singleton<BuffClientConfigCategory>
    {
        private readonly Dictionary<int, BuffClientConfig> _dataMap;
        private readonly List<BuffClientConfig> _dataList;

        public BuffClientConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BuffClientConfig>();
            _dataList = new List<BuffClientConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BuffClientConfig _v;
                _v = BuffClientConfig.DeserializeBuffClientConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BuffClientConfig> DataMap => _dataMap;
        public List<BuffClientConfig> DataList => _dataList;

        public BuffClientConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BuffClientConfig Get(int key) => _dataMap[key];
        public BuffClientConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
