
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffDotParams : BuffParams
    {
        public BuffDotParams(ByteBuf _buf) : base(_buf) 
        {
            Count = _buf.ReadInt();

            PostInit();
        }

        public static BuffDotParams DeserializeBuffDotParams(ByteBuf _buf)
        {
            return new BuffDotParams(_buf);
        }

        public readonly int Count;

        public const int __ID__ = -1651688196;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
