
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : BeanBase
    {
        public BuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = (BuffType)_buf.ReadInt();
            ContinueTime = _buf.ReadLong();
            Parameters = BuffParams.DeserializeBuffParams(_buf);

            PostInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly BuffType Type;

        /// <summary>
        /// 持续时长（ms）
        /// </summary>
        public readonly long ContinueTime;

        /// <summary>
        /// 参数列表
        /// </summary>
        public readonly BuffParams Parameters;

        public const int __ID__ = -1370631787;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "ContinueTime:" + ContinueTime + ","
            + "Parameters:" + Parameters + ","
            + "}";
        }

        partial void PostInit();
    }
}
