
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastSingle : CastSelectTargetsParams
    {
        public CastSingle(ByteBuf _buf) : base(_buf) 
        {

            PostInit();
        }

        public static CastSingle DeserializeCastSingle(ByteBuf _buf)
        {
            return new CastSingle(_buf);
        }

        public const int __ID__ = 1396579463;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
