
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastHitInfo : BeanBase
    {
        public CastHitInfo(ByteBuf _buf)
        {
            Time = _buf.ReadInt();
            HitSelf = _buf.ReadBool();
            HitAction = _buf.ReadInt();
            SelfBuff = _buf.ReadInt();
            TargetBuff = _buf.ReadInt();

            PostInit();
        }

        public static CastHitInfo DeserializeCastHitInfo(ByteBuf _buf)
        {
            return new CastHitInfo(_buf);
        }

        public readonly int Time;

        public readonly bool HitSelf;

        public readonly int HitAction;

        public ActionConfig HitActionConfig => ActionConfigCategory.Instance.GetOrDefault(HitAction);

        public readonly int SelfBuff;

        public BuffConfig SelfBuffConfig => BuffConfigCategory.Instance.GetOrDefault(SelfBuff);

        public readonly int TargetBuff;

        public BuffConfig TargetBuffConfig => BuffConfigCategory.Instance.GetOrDefault(TargetBuff);

        public const int __ID__ = -823666046;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Time:" + Time + ","
            + "HitSelf:" + HitSelf + ","
            + "HitAction:" + HitAction + ","
            + "SelfBuff:" + SelfBuff + ","
            + "TargetBuff:" + TargetBuff + ","
            + "}";
        }

        partial void PostInit();
    }
}
