
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastClientConfig : BeanBase
    {
        public CastClientConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            CastStartAnimation = _buf.ReadString();
            CastHitAnimation = _buf.ReadString();
            if(_buf.ReadBool()){ CastStartFx = _buf.ReadString(); } else { CastStartFx = null; }
            CastStartFxBindPoint = (ModelBindPoint)_buf.ReadInt();
            CastStartFxTime = _buf.ReadLong();
            if(_buf.ReadBool()){ CastHitFx = _buf.ReadString(); } else { CastHitFx = null; }
            CastHitFxBindPoint = (ModelBindPoint)_buf.ReadInt();
            CastHitFxTime = _buf.ReadLong();

            PostInit();
        }

        public static CastClientConfig DeserializeCastClientConfig(ByteBuf _buf)
        {
            return new CastClientConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能编号
        /// </summary>
        public CastConfig IdConfig => CastConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 技能起手动画
        /// </summary>
        public readonly string CastStartAnimation;

        /// <summary>
        /// 技能命中动画
        /// </summary>
        public readonly string CastHitAnimation;

        /// <summary>
        /// 技能起手特效
        /// </summary>
        public readonly string CastStartFx;

        /// <summary>
        /// 技能起手特效绑点
        /// </summary>
        public readonly ModelBindPoint CastStartFxBindPoint;

        /// <summary>
        /// 技能起手特效时长
        /// </summary>
        public readonly long CastStartFxTime;

        /// <summary>
        /// 技能命中特效
        /// </summary>
        public readonly string CastHitFx;

        /// <summary>
        /// 技能命中特效绑点
        /// </summary>
        public readonly ModelBindPoint CastHitFxBindPoint;

        /// <summary>
        /// 技能命中特效时长
        /// </summary>
        public readonly long CastHitFxTime;

        public const int __ID__ = 941771756;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "CastStartAnimation:" + CastStartAnimation + ","
            + "CastHitAnimation:" + CastHitAnimation + ","
            + "CastStartFx:" + CastStartFx + ","
            + "CastStartFxBindPoint:" + CastStartFxBindPoint + ","
            + "CastStartFxTime:" + CastStartFxTime + ","
            + "CastHitFx:" + CastHitFx + ","
            + "CastHitFxBindPoint:" + CastHitFxBindPoint + ","
            + "CastHitFxTime:" + CastHitFxTime + ","
            + "}";
        }

        partial void PostInit();
    }
}
