
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastConfig : BeanBase
    {
        public CastConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            TotalTime = _buf.ReadLong();
            CastCooldown = _buf.ReadInt();
            Casting = _buf.ReadBool();
            SelectTargetType = (SelectTargetType)_buf.ReadInt();
            CastTargetType = (CastTargetType)_buf.ReadInt();
            SelectTargetsParams = SelectTargetsParams.DeserializeSelectTargetsParams(_buf);
            NotifyType = (MessageNotifyType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);HitInfos = new System.Collections.Generic.List<CastHitInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { CastHitInfo _e0;  _e0 = CastHitInfo.DeserializeCastHitInfo(_buf); HitInfos.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);FinishActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); FinishActions.Add(_e0);}}
            CastStartAnimation = _buf.ReadString();
            CastHitAnimation = _buf.ReadString();

            PostInit();
        }

        public static CastConfig DeserializeCastConfig(ByteBuf _buf)
        {
            return new CastConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 技能总时长
        /// </summary>
        public readonly long TotalTime;

        /// <summary>
        /// 技能释放CD
        /// </summary>
        public readonly int CastCooldown;

        /// <summary>
        /// 持续施法
        /// </summary>
        public readonly bool Casting;

        /// <summary>
        /// 技能选择目标类型
        /// </summary>
        public readonly SelectTargetType SelectTargetType;

        /// <summary>
        /// 技能释放阵营
        /// </summary>
        public readonly CastTargetType CastTargetType;

        public readonly SelectTargetsParams SelectTargetsParams;

        /// <summary>
        /// 通知客户端方式
        /// </summary>
        public readonly MessageNotifyType NotifyType;

        /// <summary>
        /// 命中信息
        /// </summary>
        public readonly System.Collections.Generic.List<CastHitInfo> HitInfos;

        /// <summary>
        /// 结束行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> FinishActions;

        /// <summary>
        /// 技能起手动画
        /// </summary>
        public readonly string CastStartAnimation;

        /// <summary>
        /// 技能受击动画
        /// </summary>
        public readonly string CastHitAnimation;

        public const int __ID__ = 944053121;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "TotalTime:" + TotalTime + ","
            + "CastCooldown:" + CastCooldown + ","
            + "Casting:" + Casting + ","
            + "SelectTargetType:" + SelectTargetType + ","
            + "CastTargetType:" + CastTargetType + ","
            + "SelectTargetsParams:" + SelectTargetsParams + ","
            + "NotifyType:" + NotifyType + ","
            + "HitInfos:" + Luban.StringUtil.CollectionToString(HitInfos) + ","
            + "FinishActions:" + Luban.StringUtil.CollectionToString(FinishActions) + ","
            + "CastStartAnimation:" + CastStartAnimation + ","
            + "CastHitAnimation:" + CastHitAnimation + ","
            + "}";
        }

        partial void PostInit();
    }
}
