
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastClientConfig : BeanBase
    {
        public CastClientConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            CastStartAnimation = _buf.ReadString();
            CastHitAnimation = _buf.ReadString();

            PostInit();
        }

        public static CastClientConfig DeserializeCastClientConfig(ByteBuf _buf)
        {
            return new CastClientConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能编号
        /// </summary>
        public CastConfig IdConfig => CastConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 技能起手动画
        /// </summary>
        public readonly string CastStartAnimation;

        /// <summary>
        /// 技能受击动画
        /// </summary>
        public readonly string CastHitAnimation;

        public const int __ID__ = 941771756;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "CastStartAnimation:" + CastStartAnimation + ","
            + "CastHitAnimation:" + CastHitAnimation + ","
            + "}";
        }

        partial void PostInit();
    }
}
