
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum CastTargetType
    {
        /// <summary>
        /// 友方
        /// </summary>
        CastTargetType_SelfCamp = 1,

        /// <summary>
        /// 敌方
        /// </summary>
        CastTargetType_EnemyCamp = 2,

    }
}
