
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CastTargetCycle : CastSelectTargetsParams
    {
        public CastTargetCycle(ByteBuf _buf) : base(_buf) 
        {
            IncludeSelf = _buf.ReadBool();
            Radius = _buf.ReadInt();
            Counter = _buf.ReadInt();

            PostInit();
        }

        public static CastTargetCycle DeserializeCastTargetCycle(ByteBuf _buf)
        {
            return new CastTargetCycle(_buf);
        }

        public readonly bool IncludeSelf;

        public readonly int Radius;

        public readonly int Counter;

        public const int __ID__ = -1603125002;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "IncludeSelf:" + IncludeSelf + ","
            + "Radius:" + Radius + ","
            + "Counter:" + Counter + ","
            + "}";
        }

        partial void PostInit();
    }
}
