
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 支付商城配置
    /// </summary>
    [Config]
    public partial class ChargeConfigCategory : Singleton<ChargeConfigCategory>
    {
        private readonly Dictionary<string, ChargeConfig> _dataMap;
        private readonly List<ChargeConfig> _dataList;

        public ChargeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<string, ChargeConfig>();
            _dataList = new List<ChargeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ChargeConfig _v;
                _v = ChargeConfig.DeserializeChargeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<string, ChargeConfig> DataMap => _dataMap;
        public List<ChargeConfig> DataList => _dataList;

        public ChargeConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ChargeConfig Get(string key) => _dataMap[key];
        public ChargeConfig this[string key] => _dataMap[key];

        partial void PostInit();
    }
}
