
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ChatChannel
    {
        /// <summary>
        /// 世界频道
        /// </summary>
        ChatChannel_World = 1,

        /// <summary>
        /// 工会频道
        /// </summary>
        ChatChannel_Guild = 2,

        /// <summary>
        /// 聊天频道最大值
        /// </summary>
        ChatChannel_Max = 3,

    }
}
