
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class Condition : BeanBase
    {
        public Condition(ByteBuf _buf)
        {

            PostInit();
        }

        public static Condition DeserializeCondition(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case PropertyCompare.__ID__: return new PropertyCompare(_buf);
                case CurrencyCompare.__ID__: return new CurrencyCompare(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
