
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CreateRoleConfig : BeanBase
    {
        public CreateRoleConfig(ByteBuf _buf)
        {
            Id = (CharacterType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Items = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     Items.Add(_k0, _v0);}}
            CurrencyType = (CurrencyType)_buf.ReadInt();
            CurrencyValue = _buf.ReadLong();
            RaceFlag = (RaceType)_buf.ReadInt();
            BaseProperty = _buf.ReadInt();

            PostInit();
        }

        public static CreateRoleConfig DeserializeCreateRoleConfig(ByteBuf _buf)
        {
            return new CreateRoleConfig(_buf);
        }

        /// <summary>
        /// 职业
        /// </summary>
        public readonly CharacterType Id;

        /// <summary>
        /// 初始道具
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, long> Items;

        /// <summary>
        /// 初始货币类型
        /// </summary>
        public readonly CurrencyType CurrencyType;

        /// <summary>
        /// 初始货币值
        /// </summary>
        public readonly long CurrencyValue;

        /// <summary>
        /// 职业种族
        /// </summary>
        public readonly RaceType RaceFlag;

        /// <summary>
        /// 基础属性包
        /// </summary>
        public readonly int BaseProperty;

        /// <summary>
        /// 基础属性包
        /// </summary>
        public PropertyConfig BasePropertyConfig => PropertyConfigCategory.Instance.GetOrDefault(BaseProperty);

        public const int __ID__ = 2003629460;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Items:" + Luban.StringUtil.CollectionToString(Items) + ","
            + "CurrencyType:" + CurrencyType + ","
            + "CurrencyValue:" + CurrencyValue + ","
            + "RaceFlag:" + RaceFlag + ","
            + "BaseProperty:" + BaseProperty + ","
            + "}";
        }

        partial void PostInit();
    }
}
