
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum CurrencyType
    {
        /// <summary>
        /// 银币
        /// </summary>
        CurrencyType_Silver = 1,

        /// <summary>
        /// 金币
        /// </summary>
        CurrencyType_Gold = 2,

        /// <summary>
        /// 钻石
        /// </summary>
        CurrencyType_Diamond = 3,

        CurrencyType_Max = 4,

    }
}
