
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 日常活动配置表
    /// </summary>
    [Config]
    public partial class DailyConfigCategory : Singleton<DailyConfigCategory>
    {
        private readonly Dictionary<int, DailyConfig> _dataMap;
        private readonly List<DailyConfig> _dataList;

        public DailyConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, DailyConfig>();
            _dataList = new List<DailyConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                DailyConfig _v;
                _v = DailyConfig.DeserializeDailyConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, DailyConfig> DataMap => _dataMap;
        public List<DailyConfig> DataList => _dataList;

        public DailyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public DailyConfig Get(int key) => _dataMap[key];
        public DailyConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
