
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DamageActionParams : ActionParam
    {
        public DamageActionParams(ByteBuf _buf) : base(_buf) 
        {
            AdditionalDamage = _buf.ReadLong();

            PostInit();
        }

        public static DamageActionParams DeserializeDamageActionParams(ByteBuf _buf)
        {
            return new DamageActionParams(_buf);
        }

        public readonly long AdditionalDamage;

        public const int __ID__ = 902713483;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "AdditionalDamage:" + AdditionalDamage + ","
            + "}";
        }

        partial void PostInit();
    }
}
