
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DropConfig : BeanBase
    {
        public DropConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            DropCount = _buf.ReadInt();
            DropCertainty = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DropList = new System.Collections.Generic.List<DropItem>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { DropItem _e0;  _e0 = DropItem.DeserializeDropItem(_buf); DropList.Add(_e0);}}

            PostInit();
        }

        public static DropConfig DeserializeDropConfig(ByteBuf _buf)
        {
            return new DropConfig(_buf);
        }

        public readonly int Id;

        public readonly int DropCount;

        public readonly int DropCertainty;

        public readonly System.Collections.Generic.List<DropItem> DropList;

        public const int __ID__ = -1845736655;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DropCount:" + DropCount + ","
            + "DropCertainty:" + DropCertainty + ","
            + "DropList:" + Luban.StringUtil.CollectionToString(DropList) + ","
            + "}";
        }

        partial void PostInit();
    }
}
