
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// UI配置表
    /// </summary>
    [Config]
    public partial class ExpConfigCategory : Singleton<ExpConfigCategory>
    {
        private readonly Dictionary<int, ExpConfig> _dataMap;
        private readonly List<ExpConfig> _dataList;

        public ExpConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ExpConfig>();
            _dataList = new List<ExpConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ExpConfig _v;
                _v = ExpConfig.DeserializeExpConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ExpConfig> DataMap => _dataMap;
        public List<ExpConfig> DataList => _dataList;

        public ExpConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ExpConfig Get(int key) => _dataMap[key];
        public ExpConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
