
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum GameItemQualityType
    {
        /// <summary>
        /// 白色品质
        /// </summary>
        GameItemQualityType_White = 1,

        /// <summary>
        /// 绿色品质
        /// </summary>
        GameItemQualityType_Green = 2,

        /// <summary>
        /// 蓝色品质
        /// </summary>
        GameItemQualityType_Blue = 3,

        /// <summary>
        /// 紫色品质
        /// </summary>
        GameItemQualityType_Purple = 4,

        /// <summary>
        /// 橙色品质
        /// </summary>
        GameItemQualityType_Orange = 5,

        /// <summary>
        /// 红色品质
        /// </summary>
        GameItemQualityType_Red = 6,

    }
}
