
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum GameItemType
    {
        /// <summary>
        /// 普通
        /// </summary>
        GameItemType_Normal = 1,

        /// <summary>
        /// 货币
        /// </summary>
        GameItemType_Money = 2,

        /// <summary>
        /// 装备
        /// </summary>
        GameItemType_Equipment = 3,

        /// <summary>
        /// 药品
        /// </summary>
        GameItemType_Medicine = 4,

        /// <summary>
        /// 材料
        /// </summary>
        GameItemType_Material = 5,

        /// <summary>
        /// 碎片
        /// </summary>
        GameItemType_Fragment = 6,

    }
}
