
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 宝石配置表
    /// </summary>
    [Config]
    public partial class GemConfigCategory : Singleton<GemConfigCategory>
    {
        private readonly Dictionary<int, GemConfig> _dataMap;
        private readonly List<GemConfig> _dataList;

        public GemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, GemConfig>();
            _dataList = new List<GemConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                GemConfig _v;
                _v = GemConfig.DeserializeGemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, GemConfig> DataMap => _dataMap;
        public List<GemConfig> DataList => _dataList;

        public GemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public GemConfig Get(int key) => _dataMap[key];
        public GemConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
