
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : BeanBase
    {
        public ItemConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Reward = new System.Collections.Generic.Dictionary<int, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Reward.Add(_k0, _v0);}}
            UseLevel = _buf.ReadInt();

            PostInit();
        }

        public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
        {
            return new ItemConfig(_buf);
        }

        /// <summary>
        /// 道具id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 道具名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 奖励包内容
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, int> Reward;

        /// <summary>
        /// 道具使用等级限制
        /// </summary>
        public readonly int UseLevel;

        public const int __ID__ = -764023723;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
            + "UseLevel:" + UseLevel + ","
            + "}";
        }

        partial void PostInit();
    }
}
