
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum MessageNotifyType
    {
        /// <summary>
        /// 通知当前玩家
        /// </summary>
        MessageNotifyType_Self = 1,

        /// <summary>
        /// 通知视野内所有玩家
        /// </summary>
        MessageNotifyType_Broadcast = 2,

        /// <summary>
        /// 通知视野内所有玩家除了自己
        /// </summary>
        MessageNotifyType_BroadcastExceptMe = 3,

    }
}
