
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterCreationInfo : BeanBase
    {
        public MonsterCreationInfo(ByteBuf _buf)
        {
            MonsterConfig = _buf.ReadInt();
            MonsterCount = _buf.ReadInt();

            PostInit();
        }

        public static MonsterCreationInfo DeserializeMonsterCreationInfo(ByteBuf _buf)
        {
            return new MonsterCreationInfo(_buf);
        }

        public readonly int MonsterConfig;

        public UnitConfig MonsterConfigConfig => UnitConfigCategory.Instance.GetOrDefault(MonsterConfig);

        public readonly int MonsterCount;

        public const int __ID__ = -2020004601;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "MonsterConfig:" + MonsterConfig + ","
            + "MonsterCount:" + MonsterCount + ","
            + "}";
        }

        partial void PostInit();
    }
}
