
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 属性配置表
    /// </summary>
    [Config]
    public partial class PropertyConfigCategory : Singleton<PropertyConfigCategory>
    {
        private readonly Dictionary<int, PropertyConfig> _dataMap;
        private readonly List<PropertyConfig> _dataList;

        public PropertyConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PropertyConfig>();
            _dataList = new List<PropertyConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PropertyConfig _v;
                _v = PropertyConfig.DeserializePropertyConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PropertyConfig> DataMap => _dataMap;
        public List<PropertyConfig> DataList => _dataList;

        public PropertyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public PropertyConfig Get(int key) => _dataMap[key];
        public PropertyConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
