
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PropertyCompare : Condition
    {
        public PropertyCompare(ByteBuf _buf) : base(_buf) 
        {
            Property = (GamePropertyType)_buf.ReadInt();
            Value = _buf.ReadInt();

            PostInit();
        }

        public static PropertyCompare DeserializePropertyCompare(ByteBuf _buf)
        {
            return new PropertyCompare(_buf);
        }

        public readonly GamePropertyType Property;

        public readonly int Value;

        public const int __ID__ = -585341648;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Property:" + Property + ","
            + "Value:" + Value + ","
            + "}";
        }

        partial void PostInit();
    }
}
