
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 奖励配置表
    /// </summary>
    [Config]
    public partial class RewardConfigCategory : Singleton<RewardConfigCategory>
    {
        private readonly Dictionary<int, RewardConfig> _dataMap;
        private readonly List<RewardConfig> _dataList;

        public RewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, RewardConfig>();
            _dataList = new List<RewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                RewardConfig _v;
                _v = RewardConfig.DeserializeRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, RewardConfig> DataMap => _dataMap;
        public List<RewardConfig> DataList => _dataList;

        public RewardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public RewardConfig Get(int key) => _dataMap[key];
        public RewardConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
