
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SceneConfig : BeanBase
    {
        public SceneConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SceneRes = _buf.ReadString();

            PostInit();
        }

        public static SceneConfig DeserializeSceneConfig(ByteBuf _buf)
        {
            return new SceneConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 场景资源编号
        /// </summary>
        public readonly string SceneRes;

        public const int __ID__ = 935827150;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SceneRes:" + SceneRes + ","
            + "}";
        }

        partial void PostInit();
    }
}
