
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class SkillTargetRangeParams : BeanBase
    {
        public SkillTargetRangeParams(ByteBuf _buf)
        {

            PostInit();
        }

        public static SkillTargetRangeParams DeserializeSkillTargetRangeParams(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case SkillTargetSingle.__ID__: return new SkillTargetSingle(_buf);
                case SkillTargetCycle.__ID__: return new SkillTargetCycle(_buf);
                case SkillTargetRect.__ID__: return new SkillTargetRect(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
