
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillTargetCycle : SkillTargetRangeParams
    {
        public SkillTargetCycle(ByteBuf _buf) : base(_buf) 
        {
            IncludeSelf = _buf.ReadBool();
            Radius = _buf.ReadInt();

            PostInit();
        }

        public static SkillTargetCycle DeserializeSkillTargetCycle(ByteBuf _buf)
        {
            return new SkillTargetCycle(_buf);
        }

        public readonly bool IncludeSelf;

        public readonly int Radius;

        public const int __ID__ = 416399076;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "IncludeSelf:" + IncludeSelf + ","
            + "Radius:" + Radius + ","
            + "}";
        }

        partial void PostInit();
    }
}
