
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillTargetRect : SkillTargetRangeParams
    {
        public SkillTargetRect(ByteBuf _buf) : base(_buf) 
        {
            Width = _buf.ReadInt();
            Height = _buf.ReadInt();

            PostInit();
        }

        public static SkillTargetRect DeserializeSkillTargetRect(ByteBuf _buf)
        {
            return new SkillTargetRect(_buf);
        }

        public readonly int Width;

        public readonly int Height;

        public const int __ID__ = 13859878;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Width:" + Width + ","
            + "Height:" + Height + ","
            + "}";
        }

        partial void PostInit();
    }
}
