
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum SkillRange
    {
        /// <summary>
        /// 单体
        /// </summary>
        SkillRange_Single = 1,

        /// <summary>
        /// 自身周围圆形
        /// </summary>
        SkillRange_SelfRound = 2,

        /// <summary>
        /// 前方矩形
        /// </summary>
        SkillRange_ForwardRect = 3,

        /// <summary>
        /// 前方180度扇形
        /// </summary>
        SkillRange_ForwardSector180 = 4,

        /// <summary>
        /// 前方90度扇形
        /// </summary>
        SkillRange_ForwardSector90 = 5,

    }
}
