
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵天赋行为配置
    /// </summary>
    [Config]
    public partial class SoulTalentActionConfigCategory : Singleton<SoulTalentActionConfigCategory>
    {
        private readonly Dictionary<int, SoulTalentActionConfig> _dataMap;
        private readonly List<SoulTalentActionConfig> _dataList;

        public SoulTalentActionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulTalentActionConfig>();
            _dataList = new List<SoulTalentActionConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulTalentActionConfig _v;
                _v = SoulTalentActionConfig.DeserializeSoulTalentActionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulTalentActionConfig> DataMap => _dataMap;
        public List<SoulTalentActionConfig> DataList => _dataList;

        public SoulTalentActionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulTalentActionConfig Get(int key) => _dataMap[key];
        public SoulTalentActionConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
