
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵-buff配置
    /// </summary>
    [Config]
    public partial class SoulBuffConfigCategory : Singleton<SoulBuffConfigCategory>
    {
        private readonly Dictionary<int, SoulBuffConfig> _dataMap;
        private readonly List<SoulBuffConfig> _dataList;

        public SoulBuffConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulBuffConfig>();
            _dataList = new List<SoulBuffConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulBuffConfig _v;
                _v = SoulBuffConfig.DeserializeSoulBuffConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulBuffConfig> DataMap => _dataMap;
        public List<SoulBuffConfig> DataList => _dataList;

        public SoulBuffConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulBuffConfig Get(int key) => _dataMap[key];
        public SoulBuffConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
