
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulCastConfig : BeanBase
    {
        public SoulCastConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            TotalTime = _buf.ReadLong();
            CastCooldown = _buf.ReadInt();
            SelectTargetType = (SelectTargetType)_buf.ReadInt();
            CastTargetType = (CastTargetType)_buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);HitInfos = new System.Collections.Generic.List<CastHitInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { CastHitInfo _e0;  _e0 = CastHitInfo.DeserializeCastHitInfo(_buf); HitInfos.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);FinishActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); FinishActions.Add(_e0);}}

            PostInit();
        }

        public static SoulCastConfig DeserializeSoulCastConfig(ByteBuf _buf)
        {
            return new SoulCastConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能总时长
        /// </summary>
        public readonly long TotalTime;

        /// <summary>
        /// 技能释放CD
        /// </summary>
        public readonly int CastCooldown;

        /// <summary>
        /// 技能选择目标类型
        /// </summary>
        public readonly SelectTargetType SelectTargetType;

        /// <summary>
        /// 技能释放阵营
        /// </summary>
        public readonly CastTargetType CastTargetType;

        /// <summary>
        /// 命中信息
        /// </summary>
        public readonly System.Collections.Generic.List<CastHitInfo> HitInfos;

        /// <summary>
        /// 结束行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> FinishActions;

        public const int __ID__ = 849955284;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TotalTime:" + TotalTime + ","
            + "CastCooldown:" + CastCooldown + ","
            + "SelectTargetType:" + SelectTargetType + ","
            + "CastTargetType:" + CastTargetType + ","
            + "HitInfos:" + Luban.StringUtil.CollectionToString(HitInfos) + ","
            + "FinishActions:" + Luban.StringUtil.CollectionToString(FinishActions) + ","
            + "}";
        }

        partial void PostInit();
    }
}
