
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵-行为配置
    /// </summary>
    [Config]
    public partial class SoulActionConfigCategory : Singleton<SoulActionConfigCategory>
    {
        private readonly Dictionary<int, SoulActionConfig> _dataMap;
        private readonly List<SoulActionConfig> _dataList;

        public SoulActionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulActionConfig>();
            _dataList = new List<SoulActionConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulActionConfig _v;
                _v = SoulActionConfig.DeserializeSoulActionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulActionConfig> DataMap => _dataMap;
        public List<SoulActionConfig> DataList => _dataList;

        public SoulActionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulActionConfig Get(int key) => _dataMap[key];
        public SoulActionConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
