
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulTalentConfig : BeanBase
    {
        public SoulTalentConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Talent = _buf.ReadInt();

            PostInit();
        }

        public static SoulTalentConfig DeserializeSoulTalentConfig(ByteBuf _buf)
        {
            return new SoulTalentConfig(_buf);
        }

        /// <summary>
        /// 灵编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 灵编号
        /// </summary>
        public SoulConfig IdConfig => SoulConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 灵天赋行为
        /// </summary>
        public readonly int Talent;

        /// <summary>
        /// 灵天赋行为
        /// </summary>
        public SoulTalentActionConfig TalentConfig => SoulTalentActionConfigCategory.Instance.GetOrDefault(Talent);

        public const int __ID__ = -2068317951;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Talent:" + Talent + ","
            + "}";
        }

        partial void PostInit();
    }
}
