
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵-技能配置
    /// </summary>
    [Config]
    public partial class SoulCastConfigCategory : Singleton<SoulCastConfigCategory>
    {
        private readonly Dictionary<int, SoulCastConfig> _dataMap;
        private readonly List<SoulCastConfig> _dataList;

        public SoulCastConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulCastConfig>();
            _dataList = new List<SoulCastConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulCastConfig _v;
                _v = SoulCastConfig.DeserializeSoulCastConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulCastConfig> DataMap => _dataMap;
        public List<SoulCastConfig> DataList => _dataList;

        public SoulCastConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulCastConfig Get(int key) => _dataMap[key];
        public SoulCastConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
