
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SubcastParams : ActionParam
    {
        public SubcastParams(ByteBuf _buf) : base(_buf) 
        {
            SubCastConfigId = _buf.ReadInt();

            PostInit();
        }

        public static SubcastParams DeserializeSubcastParams(ByteBuf _buf)
        {
            return new SubcastParams(_buf);
        }

        public readonly int SubCastConfigId;

        public CastConfig SubCastConfigIdConfig => CastConfigCategory.Instance.GetOrDefault(SubCastConfigId);

        public const int __ID__ = -1357458491;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "SubCastConfigId:" + SubCastConfigId + ","
            + "}";
        }

        partial void PostInit();
    }
}
