
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum SubTaskType
    {
        /// <summary>
        /// 交互
        /// </summary>
        SubTaskType_Interactive = 1,

        /// <summary>
        /// 猎杀
        /// </summary>
        SubTaskType_Hunt = 2,

        /// <summary>
        /// 采集
        /// </summary>
        SubTaskType_Gather = 3,

    }
}
