
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 天赋配置表
    /// </summary>
    [Config]
    public partial class TalentConfigCategory : Singleton<TalentConfigCategory>
    {
        private readonly Dictionary<int, TalentConfig> _dataMap;
        private readonly List<TalentConfig> _dataList;

        public TalentConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TalentConfig>();
            _dataList = new List<TalentConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TalentConfig _v;
                _v = TalentConfig.DeserializeTalentConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TalentConfig> DataMap => _dataMap;
        public List<TalentConfig> DataList => _dataList;

        public TalentConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public TalentConfig Get(int key) => _dataMap[key];
        public TalentConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
