
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 陷阱配置表
    /// </summary>
    [Config]
    public partial class TrapConfigCategory : Singleton<TrapConfigCategory>
    {
        private readonly Dictionary<int, TrapConfig> _dataMap;
        private readonly List<TrapConfig> _dataList;

        public TrapConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TrapConfig>();
            _dataList = new List<TrapConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TrapConfig _v;
                _v = TrapConfig.DeserializeTrapConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TrapConfig> DataMap => _dataMap;
        public List<TrapConfig> DataList => _dataList;

        public TrapConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public TrapConfig Get(int key) => _dataMap[key];
        public TrapConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
