
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// Vip配置
    /// </summary>
    [Config]
    public partial class VipConfigCategory : Singleton<VipConfigCategory>
    {
        private readonly Dictionary<int, VipConfig> _dataMap;
        private readonly List<VipConfig> _dataList;

        public VipConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, VipConfig>();
            _dataList = new List<VipConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                VipConfig _v;
                _v = VipConfig.DeserializeVipConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.VipLevel, _v);
            }

            PostInit();
        }

        public Dictionary<int, VipConfig> DataMap => _dataMap;
        public List<VipConfig> DataList => _dataList;

        public VipConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public VipConfig Get(int key) => _dataMap[key];
        public VipConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
