
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class ActionParam : BeanBase
    {
        public ActionParam(ByteBuf _buf)
        {

            PostInit();
        }

        public static ActionParam DeserializeActionParam(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case ModifyPropertyActionParams.__ID__: return new ModifyPropertyActionParams(_buf);
                case DamageActionParams.__ID__: return new DamageActionParams(_buf);
                case SubcastParams.__ID__: return new SubcastParams(_buf);
                case MoveToTargetParams.__ID__: return new MoveToTargetParams(_buf);
                case AttractParams.__ID__: return new AttractParams(_buf);
                case HitFlyParams.__ID__: return new HitFlyParams(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
