
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AICastParam : AIParam
    {
        public AICastParam(ByteBuf _buf) : base(_buf) 
        {
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CastConfigIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CastConfigIds.Add(_e0);}}

            PostInit();
        }

        public static AICastParam DeserializeAICastParam(ByteBuf _buf)
        {
            return new AICastParam(_buf);
        }

        public readonly System.Collections.Generic.List<int> CastConfigIds;

        public const int __ID__ = 791781702;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "CastConfigIds:" + Luban.StringUtil.CollectionToString(CastConfigIds) + ","
            + "}";
        }

        partial void PostInit();
    }
}
