
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// AI节点配置
    /// </summary>
    [Config]
    public partial class AINodeConfigCategory : Singleton<AINodeConfigCategory>
    {
        private readonly Dictionary<int, AINodeConfig> _dataMap;
        private readonly List<AINodeConfig> _dataList;

        public AINodeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, AINodeConfig>();
            _dataList = new List<AINodeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AINodeConfig _v;
                _v = AINodeConfig.DeserializeAINodeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, AINodeConfig> DataMap => _dataMap;
        public List<AINodeConfig> DataList => _dataList;

        public AINodeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public AINodeConfig Get(int key) => _dataMap[key];
        public AINodeConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
