
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AINodeConfig : BeanBase
    {
        public AINodeConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = (AIType)_buf.ReadInt();
            AIParams = AIParam.DeserializeAIParam(_buf);

            PostInit();
        }

        public static AINodeConfig DeserializeAINodeConfig(ByteBuf _buf)
        {
            return new AINodeConfig(_buf);
        }

        /// <summary>
        /// AI节点编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// AI节点类型
        /// </summary>
        public readonly AIType Type;

        public readonly AIParam AIParams;

        public const int __ID__ = 214820396;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "AIParams:" + AIParams + ","
            + "}";
        }

        partial void PostInit();
    }
}
