
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum AIType
    {
        /// <summary>
        /// 巡逻
        /// </summary>
        AIType_XunLuo = 1,

        /// <summary>
        /// 自动释放技能
        /// </summary>
        AIType_AutoSkill = 2,

        /// <summary>
        /// 发呆
        /// </summary>
        AIType_Stand = 3,

        /// <summary>
        /// 自动任务
        /// </summary>
        AIType_AutoTask = 4,

        /// <summary>
        /// 巡逻1
        /// </summary>
        AIType_Patrol = 5,

    }
}
