
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum AvocationType
    {
        /// <summary>
        /// 钓鱼
        /// </summary>
        AvocationType_Fishing = 1,

        /// <summary>
        /// 考古
        /// </summary>
        AvocationType_Archaeology = 2,

        /// <summary>
        /// 烹饪
        /// </summary>
        AvocationType_Cooking = 3,

    }
}
