
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BattleAttributeConfig : BeanBase
    {
        public BattleAttributeConfig(ByteBuf _buf)
        {
            Id = (BattleAttribute)_buf.ReadInt();
            DestAttribute = (BattleAttribute)_buf.ReadInt();
            DamageRatio = _buf.ReadLong();

            PostInit();
        }

        public static BattleAttributeConfig DeserializeBattleAttributeConfig(ByteBuf _buf)
        {
            return new BattleAttributeConfig(_buf);
        }

        /// <summary>
        /// 攻击者属性
        /// </summary>
        public readonly BattleAttribute Id;

        /// <summary>
        /// 受击者属性
        /// </summary>
        public readonly BattleAttribute DestAttribute;

        /// <summary>
        /// 伤害加成
        /// </summary>
        public readonly long DamageRatio;

        public const int __ID__ = -1180048122;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DestAttribute:" + DestAttribute + ","
            + "DamageRatio:" + DamageRatio + ","
            + "}";
        }

        partial void PostInit();
    }
}
