
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum BattleAttribute
    {
        /// <summary>
        /// 火
        /// </summary>
        BattleAttribute_Fire = 1,

        /// <summary>
        /// 水
        /// </summary>
        BattleAttribute_Water = 2,

        /// <summary>
        /// 木
        /// </summary>
        BattleAttribute_Wood = 3,

        /// <summary>
        /// 光
        /// </summary>
        BattleAttribute_Light = 4,

        /// <summary>
        /// 暗
        /// </summary>
        BattleAttribute_Dark = 5,

    }
}
