
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffControlParams : BuffParams
    {
        public BuffControlParams(ByteBuf _buf) : base(_buf) 
        {
            Type = (BuffControlType)_buf.ReadInt();

            PostInit();
        }

        public static BuffControlParams DeserializeBuffControlParams(ByteBuf _buf)
        {
            return new BuffControlParams(_buf);
        }

        public readonly BuffControlType Type;

        public const int __ID__ = 225087376;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Type:" + Type + ","
            + "}";
        }

        partial void PostInit();
    }
}
