
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum BuffType
    {
        /// <summary>
        /// 修改属性值
        /// </summary>
        BuffType_ModifyProperty = 1,

        /// <summary>
        /// 控制类
        /// </summary>
        BuffType_Control = 2,

        /// <summary>
        /// 持续伤害
        /// </summary>
        BuffType_ContinueDamage = 3,

        /// <summary>
        /// 响应行动
        /// </summary>
        BuffType_Action = 4,

    }
}
