
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffActionParams : BuffParams
    {
        public BuffActionParams(ByteBuf _buf) : base(_buf) 
        {
            ActionType = (BuffActionType)_buf.ReadInt();

            PostInit();
        }

        public static BuffActionParams DeserializeBuffActionParams(ByteBuf _buf)
        {
            return new BuffActionParams(_buf);
        }

        public readonly BuffActionType ActionType;

        public const int __ID__ = -1661311121;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "ActionType:" + ActionType + ","
            + "}";
        }

        partial void PostInit();
    }
}
