
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum BuffProperty
    {
        /// <summary>
        /// 魔法
        /// </summary>
        BuffProperty_Magic = 1,

        /// <summary>
        /// 疾病
        /// </summary>
        BuffProperty_Disease = 2,

        /// <summary>
        /// 诅咒
        /// </summary>
        BuffProperty_Curse = 3,

    }
}
