
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class CastSelectTargetsParams : BeanBase
    {
        public CastSelectTargetsParams(ByteBuf _buf)
        {

            PostInit();
        }

        public static CastSelectTargetsParams DeserializeCastSelectTargetsParams(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case CastSingle.__ID__: return new CastSingle(_buf);
                case CastTargetCycle.__ID__: return new CastTargetCycle(_buf);
                case CastForwardRect.__ID__: return new CastForwardRect(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
