
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum DailyType
    {
        /// <summary>
        /// 每日
        /// </summary>
        DailyType_Daily = 1,

        /// <summary>
        /// 每周
        /// </summary>
        DailyType_Weeky = 2,

        /// <summary>
        /// 每月
        /// </summary>
        DailyType_Monthy = 3,

        /// <summary>
        /// 指定一周内的某几天
        /// </summary>
        DailyType_Days = 4,

    }
}
