
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DisperseParams : ActionParam
    {
        public DisperseParams(ByteBuf _buf) : base(_buf) 
        {
            Type = _buf.ReadInt();
            Count = _buf.ReadInt();

            PostInit();
        }

        public static DisperseParams DeserializeDisperseParams(ByteBuf _buf)
        {
            return new DisperseParams(_buf);
        }

        public readonly int Type;

        public readonly int Count;

        public const int __ID__ = -368954009;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Type:" + Type + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
