
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 掉落配置
    /// </summary>
    [Config]
    public partial class DropConfigCategory : Singleton<DropConfigCategory>
    {
        private readonly Dictionary<int, DropConfig> _dataMap;
        private readonly List<DropConfig> _dataList;

        public DropConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, DropConfig>();
            _dataList = new List<DropConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                DropConfig _v;
                _v = DropConfig.DeserializeDropConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, DropConfig> DataMap => _dataMap;
        public List<DropConfig> DataList => _dataList;

        public DropConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public DropConfig Get(int key) => _dataMap[key];
        public DropConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
