
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DropItem : BeanBase
    {
        public DropItem(ByteBuf _buf)
        {
            ItemConfig = _buf.ReadInt();
            ItemAmount = _buf.ReadLong();
            ItemRate = _buf.ReadInt();

            PostInit();
        }

        public static DropItem DeserializeDropItem(ByteBuf _buf)
        {
            return new DropItem(_buf);
        }

        public readonly int ItemConfig;

        public readonly long ItemAmount;

        public readonly int ItemRate;

        public const int __ID__ = -368217406;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "ItemConfig:" + ItemConfig + ","
            + "ItemAmount:" + ItemAmount + ","
            + "ItemRate:" + ItemRate + ","
            + "}";
        }

        partial void PostInit();
    }
}
