
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EquipmentHoleConfig : BeanBase
    {
        public EquipmentHoleConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);HolesProperty = new System.Collections.Generic.Dictionary<int, EquipmentHoles>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); EquipmentHoles _v0;  _v0 = EquipmentHoles.DeserializeEquipmentHoles(_buf);     HolesProperty.Add(_k0, _v0);}}

            PostInit();
        }

        public static EquipmentHoleConfig DeserializeEquipmentHoleConfig(ByteBuf _buf)
        {
            return new EquipmentHoleConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 宝石孔位和属性
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<int, EquipmentHoles> HolesProperty;

        public const int __ID__ = 430523440;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "HolesProperty:" + Luban.StringUtil.CollectionToString(HolesProperty) + ","
            + "}";
        }

        partial void PostInit();
    }
}
