
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ExpConfig : BeanBase
    {
        public ExpConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Exp = _buf.ReadLong();
            Property = _buf.ReadInt();

            PostInit();
        }

        public static ExpConfig DeserializeExpConfig(ByteBuf _buf)
        {
            return new ExpConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 经验值
        /// </summary>
        public readonly long Exp;

        /// <summary>
        /// 等级属性包
        /// </summary>
        public readonly int Property;

        /// <summary>
        /// 等级属性包
        /// </summary>
        public PropertyConfig PropertyConfig => PropertyConfigCategory.Instance.GetOrDefault(Property);

        public const int __ID__ = 1163743135;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Exp:" + Exp + ","
            + "Property:" + Property + ","
            + "}";
        }

        partial void PostInit();
    }
}
