
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ForwardSector180 : SelectTargetsParams
    {
        public ForwardSector180(ByteBuf _buf) : base(_buf) 
        {
            Radius = _buf.ReadInt();
            Count = _buf.ReadInt();

            PostInit();
        }

        public static ForwardSector180 DeserializeForwardSector180(ByteBuf _buf)
        {
            return new ForwardSector180(_buf);
        }

        public readonly int Radius;

        public readonly int Count;

        public const int __ID__ = 198935710;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Radius:" + Radius + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
