
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GameItemUseCurrency : GameItemUseParam
    {
        public GameItemUseCurrency(ByteBuf _buf) : base(_buf) 
        {
            CurrencyType = (CurrencyType)_buf.ReadInt();
            CurrencyValue = _buf.ReadLong();

            PostInit();
        }

        public static GameItemUseCurrency DeserializeGameItemUseCurrency(ByteBuf _buf)
        {
            return new GameItemUseCurrency(_buf);
        }

        public readonly CurrencyType CurrencyType;

        public readonly long CurrencyValue;

        public const int __ID__ = 115394355;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "CurrencyType:" + CurrencyType + ","
            + "CurrencyValue:" + CurrencyValue + ","
            + "}";
        }

        partial void PostInit();
    }
}
