
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class GameItemUseParam : BeanBase
    {
        public GameItemUseParam(ByteBuf _buf)
        {

            PostInit();
        }

        public static GameItemUseParam DeserializeGameItemUseParam(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case GameItemUseCurrency.__ID__: return new GameItemUseCurrency(_buf);
                case GameItemUseTask.__ID__: return new GameItemUseTask(_buf);
                case GameItemUseBuff.__ID__: return new GameItemUseBuff(_buf);
                default: throw new SerializationException();
            }
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
