
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GameItemUseBuff : GameItemUseParam
    {
        public GameItemUseBuff(ByteBuf _buf) : base(_buf) 
        {
            BuffConfigId = _buf.ReadInt();

            PostInit();
        }

        public static GameItemUseBuff DeserializeGameItemUseBuff(ByteBuf _buf)
        {
            return new GameItemUseBuff(_buf);
        }

        public readonly int BuffConfigId;

        public BuffConfig BuffConfigIdConfig => BuffConfigCategory.Instance.GetOrDefault(BuffConfigId);

        public const int __ID__ = 1384122485;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "BuffConfigId:" + BuffConfigId + ","
            + "}";
        }

        partial void PostInit();
    }
}
