
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GameItemUseTask : GameItemUseParam
    {
        public GameItemUseTask(ByteBuf _buf) : base(_buf) 
        {
            TaskConfigId = _buf.ReadInt();

            PostInit();
        }

        public static GameItemUseTask DeserializeGameItemUseTask(ByteBuf _buf)
        {
            return new GameItemUseTask(_buf);
        }

        public readonly int TaskConfigId;

        public TaskConfig TaskConfigIdConfig => TaskConfigCategory.Instance.GetOrDefault(TaskConfigId);

        public const int __ID__ = 1384639911;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "TaskConfigId:" + TaskConfigId + ","
            + "}";
        }

        partial void PostInit();
    }
}
