
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum GemColor
    {
        /// <summary>
        /// 红色宝石
        /// </summary>
        GemColor_Red = 1,

        /// <summary>
        /// 黄色宝石
        /// </summary>
        GemColor_Yellow = 2,

        /// <summary>
        /// 蓝色宝石
        /// </summary>
        GemColor_Blue = 4,

        /// <summary>
        /// 多彩宝石
        /// </summary>
        GemColor_Colorful = 8,

    }
}
