
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum GuildMemberType
    {
        /// <summary>
        /// 工会会长
        /// </summary>
        GuildMemberType_Leader = 1,

        /// <summary>
        /// 工会成员
        /// </summary>
        GuildMemberType_Member = 2,

    }
}
