
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 道具使用配置
    /// </summary>
    [Config]
    public partial class ItemUseConfigCategory : Singleton<ItemUseConfigCategory>
    {
        private readonly Dictionary<int, ItemUseConfig> _dataMap;
        private readonly List<ItemUseConfig> _dataList;

        public ItemUseConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ItemUseConfig>();
            _dataList = new List<ItemUseConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ItemUseConfig _v;
                _v = ItemUseConfig.DeserializeItemUseConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ItemUseConfig> DataMap => _dataMap;
        public List<ItemUseConfig> DataList => _dataList;

        public ItemUseConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public ItemUseConfig Get(int key) => _dataMap[key];
        public ItemUseConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
