
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum LotteryQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        LotteryQuality_Gray = 1,

        /// <summary>
        /// 优秀
        /// </summary>
        LotteryQuality_Green = 2,

        /// <summary>
        /// 精良
        /// </summary>
        LotteryQuality_Blue = 3,

        /// <summary>
        /// 史诗
        /// </summary>
        LotteryQuality_Purple = 4,

        /// <summary>
        /// 传说
        /// </summary>
        LotteryQuality_Orange = 5,

        /// <summary>
        /// 神话
        /// </summary>
        LotteryQuality_Red = 6,

    }
}
