
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum ModelBindPoint
    {
        /// <summary>
        /// 头
        /// </summary>
        ModelHead = 1,

        /// <summary>
        /// 脖子
        /// </summary>
        ModelNeck = 2,

        /// <summary>
        /// 肩膀
        /// </summary>
        ModelShoulder = 3,

        /// <summary>
        /// 胸部
        /// </summary>
        ModelChest = 4,

        /// <summary>
        /// 左腿
        /// </summary>
        ModelLeftLeg = 5,

        /// <summary>
        /// 右腿
        /// </summary>
        ModelRightLeg = 6,

        /// <summary>
        /// 左脚
        /// </summary>
        ModelLeftFoot = 7,

        /// <summary>
        /// 右角
        /// </summary>
        ModelRightFoot = 8,

    }
}
