
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 怪物相关信息表
    /// </summary>
    [Config]
    public partial class MonsterConfigCategory : Singleton<MonsterConfigCategory>
    {
        private readonly Dictionary<int, MonsterConfig> _dataMap;
        private readonly List<MonsterConfig> _dataList;

        public MonsterConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterConfig>();
            _dataList = new List<MonsterConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MonsterConfig _v;
                _v = MonsterConfig.DeserializeMonsterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MonsterConfig> DataMap => _dataMap;
        public List<MonsterConfig> DataList => _dataList;

        public MonsterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public MonsterConfig Get(int key) => _dataMap[key];
        public MonsterConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
