
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MoveToTargetParams : ActionParam
    {
        public MoveToTargetParams(ByteBuf _buf) : base(_buf) 
        {
            Speed = _buf.ReadFloat();

            PostInit();
        }

        public static MoveToTargetParams DeserializeMoveToTargetParams(ByteBuf _buf)
        {
            return new MoveToTargetParams(_buf);
        }

        public readonly float Speed;

        public const int __ID__ = -246158621;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Speed:" + Speed + ","
            + "}";
        }

        partial void PostInit();
    }
}
