
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 离线奖励配置
    /// </summary>
    [Config]
    public partial class OfflineIncomeConfigCategory : Singleton<OfflineIncomeConfigCategory>
    {
        private readonly Dictionary<int, OfflineIncomeConfig> _dataMap;
        private readonly List<OfflineIncomeConfig> _dataList;

        public OfflineIncomeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, OfflineIncomeConfig>();
            _dataList = new List<OfflineIncomeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                OfflineIncomeConfig _v;
                _v = OfflineIncomeConfig.DeserializeOfflineIncomeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Level, _v);
            }

            PostInit();
        }

        public Dictionary<int, OfflineIncomeConfig> DataMap => _dataMap;
        public List<OfflineIncomeConfig> DataList => _dataList;

        public OfflineIncomeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public OfflineIncomeConfig Get(int key) => _dataMap[key];
        public OfflineIncomeConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
