
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum PackType
    {
        /// <summary>
        /// 固定物品
        /// </summary>
        PackType_Normal = 1,

        /// <summary>
        /// 可选物品
        /// </summary>
        PackType_Choose = 2,

        /// <summary>
        /// 随机物品
        /// </summary>
        PackType_Random = 3,

        /// <summary>
        /// 随机数量物品
        /// </summary>
        PackType_RandomCount = 4,

    }
}
