
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class Properties : BeanBase
    {
        public Properties(ByteBuf _buf)
        {
            Property = (GamePropertyType)_buf.ReadInt();
            Value = _buf.ReadLong();

            PostInit();
        }

        public static Properties DeserializeProperties(ByteBuf _buf)
        {
            return new Properties(_buf);
        }

        public readonly GamePropertyType Property;

        public readonly long Value;

        public const int __ID__ = 1067411795;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Property:" + Property + ","
            + "Value:" + Value + ","
            + "}";
        }

        partial void PostInit();
    }
}
