
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PropertyConfig : BeanBase
    {
        public PropertyConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Properties = new System.Collections.Generic.Dictionary<GamePropertyType, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { GamePropertyType _k0;  _k0 = (GamePropertyType)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Properties.Add(_k0, _v0);}}

            PostInit();
        }

        public static PropertyConfig DeserializePropertyConfig(ByteBuf _buf)
        {
            return new PropertyConfig(_buf);
        }

        /// <summary>
        /// 属性包id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 属性配置
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<GamePropertyType, int> Properties;

        public const int __ID__ = 950969751;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Properties:" + Luban.StringUtil.CollectionToString(Properties) + ","
            + "}";
        }

        partial void PostInit();
    }
}
