
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum PropertyType
    {
        /// <summary>
        /// 生命值
        /// </summary>
        PropertyType_Hp = 1001,

        /// <summary>
        /// 最大生命值
        /// </summary>
        PropertyType_MaxHp = 1002,

        /// <summary>
        /// 攻击
        /// </summary>
        PropertyType_Atk = 1003,

        /// <summary>
        /// 防御
        /// </summary>
        PropertyType_Def = 1004,

    }
}
