
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class RandomNameConfig : BeanBase
    {
        public RandomNameConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            FamilyName = _buf.ReadString();
            LastName = _buf.ReadString();

            PostInit();
        }

        public static RandomNameConfig DeserializeRandomNameConfig(ByteBuf _buf)
        {
            return new RandomNameConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 姓
        /// </summary>
        public readonly string FamilyName;

        /// <summary>
        /// 名
        /// </summary>
        public readonly string LastName;

        public const int __ID__ = 1869005552;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "FamilyName:" + FamilyName + ","
            + "LastName:" + LastName + ","
            + "}";
        }

        partial void PostInit();
    }
}
