
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum RoundBattleStage
    {
        /// <summary>
        /// 回合开始
        /// </summary>
        RoundBattleStage_RoundBegin = 1,

        /// <summary>
        /// 回合结束
        /// </summary>
        RoundBattleStage_RoundEnd = 2,

        /// <summary>
        /// 灵出手开始
        /// </summary>
        RoundBattleStage_SoulCastBegin = 3,

        /// <summary>
        /// 灵出手结束
        /// </summary>
        RoundBattleStage_SoulCastEnd = 4,

    }
}
