
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SceneMonsterConfig : BeanBase
    {
        public SceneMonsterConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Position = vec3.Deserializevec3(_buf);
            RandomRange = _buf.ReadInt();
            Monsters = MonsterCreationInfo.DeserializeMonsterCreationInfo(_buf);

            PostInit();
        }

        public static SceneMonsterConfig DeserializeSceneMonsterConfig(ByteBuf _buf)
        {
            return new SceneMonsterConfig(_buf);
        }

        /// <summary>
        /// 怪物分组编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 分组位置
        /// </summary>
        public readonly vec3 Position;

        /// <summary>
        /// 怪物随机距离
        /// </summary>
        public readonly int RandomRange;

        /// <summary>
        /// 怪物创建信息
        /// </summary>
        public readonly MonsterCreationInfo Monsters;

        public const int __ID__ = -1593310544;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Position:" + Position + ","
            + "RandomRange:" + RandomRange + ","
            + "Monsters:" + Monsters + ","
            + "}";
        }

        partial void PostInit();
    }
}
