
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum SelectTargetType
    {
        /// <summary>
        /// 单体
        /// </summary>
        SelectTargetType_Single = 1,

        /// <summary>
        /// 自身周围圆形
        /// </summary>
        SelectTargetType_Cycle = 2,

        /// <summary>
        /// 自身前方矩形
        /// </summary>
        SelectTargetType_ForwardRect = 3,

    }
}
