
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SelectCycle : SelectTargetsParams
    {
        public SelectCycle(ByteBuf _buf) : base(_buf) 
        {
            IncludeSelf = _buf.ReadBool();
            Distance = _buf.ReadInt();
            Radius = _buf.ReadInt();
            Counter = _buf.ReadInt();

            PostInit();
        }

        public static SelectCycle DeserializeSelectCycle(ByteBuf _buf)
        {
            return new SelectCycle(_buf);
        }

        public readonly bool IncludeSelf;

        public readonly int Distance;

        public readonly int Radius;

        public readonly int Counter;

        public const int __ID__ = 1857607978;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "IncludeSelf:" + IncludeSelf + ","
            + "Distance:" + Distance + ","
            + "Radius:" + Radius + ","
            + "Counter:" + Counter + ","
            + "}";
        }

        partial void PostInit();
    }
}
