
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    [System.Flags]
    public enum ShopType
    {
        /// <summary>
        /// 通用商店
        /// </summary>
        ShopType_Common = 1,

        /// <summary>
        /// 地下城商店
        /// </summary>
        ShopType_Dungeons = 2,

        /// <summary>
        /// 钻石商店
        /// </summary>
        ShopType_Diamond = 3,

        /// <summary>
        /// 秘境商店
        /// </summary>
        ShopType_Mijing = 4,

    }
}
