
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ShopConfig : BeanBase
    {
        public ShopConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ShopType = (ShopType)_buf.ReadInt();
            CurrencyType = (CurrencyType)_buf.ReadInt();
            CurrencyValue = _buf.ReadLong();
            Limit = _buf.ReadInt();

            PostInit();
        }

        public static ShopConfig DeserializeShopConfig(ByteBuf _buf)
        {
            return new ShopConfig(_buf);
        }

        /// <summary>
        /// 商品编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 商品编号
        /// </summary>
        public ItemConfig IdConfig => ItemConfigCategory.Instance.GetOrDefault(Id);

        /// <summary>
        /// 所属商店
        /// </summary>
        public readonly ShopType ShopType;

        /// <summary>
        /// 商品购买货币
        /// </summary>
        public readonly CurrencyType CurrencyType;

        /// <summary>
        /// 商品购买价格
        /// </summary>
        public readonly long CurrencyValue;

        /// <summary>
        /// 限购次数
        /// </summary>
        public readonly int Limit;

        public const int __ID__ = 396203512;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ShopType:" + ShopType + ","
            + "CurrencyType:" + CurrencyType + ","
            + "CurrencyValue:" + CurrencyValue + ","
            + "Limit:" + Limit + ","
            + "}";
        }

        partial void PostInit();
    }
}
