
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SignConfig : BeanBase
    {
        public SignConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SignReward = _buf.ReadInt();

            PostInit();
        }

        public static SignConfig DeserializeSignConfig(ByteBuf _buf)
        {
            return new SignConfig(_buf);
        }

        /// <summary>
        /// 签到天数
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 签到奖励
        /// </summary>
        public readonly int SignReward;

        /// <summary>
        /// 签到奖励
        /// </summary>
        public RewardConfig SignRewardConfig => RewardConfigCategory.Instance.GetOrDefault(SignReward);

        public const int __ID__ = 51128191;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SignReward:" + SignReward + ","
            + "}";
        }

        partial void PostInit();
    }
}
