
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillConfig : BeanBase
    {
        public SkillConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Level = _buf.ReadInt();
            SkillName = _buf.ReadString();
            SkillDesc = _buf.ReadString();
            Base = _buf.ReadLong();
            Ratio = _buf.ReadLong();
            SkillRange = (SkillRange)_buf.ReadInt();
            SkillTargetRangeParam = SkillTargetRangeParams.DeserializeSkillTargetRangeParams(_buf);
            SkillHitTime = _buf.ReadLong();
            Consume = _buf.ReadLong();
            LearnCurrencyType = (CurrencyType)_buf.ReadInt();
            LearnCurrencyValue = _buf.ReadLong();

            PostInit();
        }

        public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
        {
            return new SkillConfig(_buf);
        }

        /// <summary>
        /// 技能编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能等级
        /// </summary>
        public readonly int Level;

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string SkillName;

        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string SkillDesc;

        /// <summary>
        /// 基础伤害/治疗值
        /// </summary>
        public readonly long Base;

        /// <summary>
        /// 附加百分比值
        /// </summary>
        public readonly long Ratio;

        /// <summary>
        /// 技能范围
        /// </summary>
        public readonly SkillRange SkillRange;

        public readonly SkillTargetRangeParams SkillTargetRangeParam;

        /// <summary>
        /// 技能命中时间
        /// </summary>
        public readonly long SkillHitTime;

        /// <summary>
        /// 技能消耗
        /// </summary>
        public readonly long Consume;

        /// <summary>
        /// 学习花费货币类型
        /// </summary>
        public readonly CurrencyType LearnCurrencyType;

        /// <summary>
        /// 学习花费货币
        /// </summary>
        public readonly long LearnCurrencyValue;

        public const int __ID__ = -844226349;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "SkillName:" + SkillName + ","
            + "SkillDesc:" + SkillDesc + ","
            + "Base:" + Base + ","
            + "Ratio:" + Ratio + ","
            + "SkillRange:" + SkillRange + ","
            + "SkillTargetRangeParam:" + SkillTargetRangeParam + ","
            + "SkillHitTime:" + SkillHitTime + ","
            + "Consume:" + Consume + ","
            + "LearnCurrencyType:" + LearnCurrencyType + ","
            + "LearnCurrencyValue:" + LearnCurrencyValue + ","
            + "}";
        }

        partial void PostInit();
    }
}
