
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulConfig : BeanBase
    {
        public SoulConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();

            PostInit();
        }

        public static SoulConfig DeserializeSoulConfig(ByteBuf _buf)
        {
            return new SoulConfig(_buf);
        }

        /// <summary>
        /// 灵编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 灵名称
        /// </summary>
        public readonly string Name;

        public const int __ID__ = -1054163147;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "}";
        }

        partial void PostInit();
    }
}
