
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulRuneConfig : BeanBase
    {
        public SoulRuneConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();

            PostInit();
        }

        public static SoulRuneConfig DeserializeSoulRuneConfig(ByteBuf _buf)
        {
            return new SoulRuneConfig(_buf);
        }

        /// <summary>
        /// 灵符文编号
        /// </summary>
        public readonly int Id;

        public const int __ID__ = -143901297;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "}";
        }

        partial void PostInit();
    }
}
