
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵符文配置
    /// </summary>
    [Config]
    public partial class SoulRuneConfigCategory : Singleton<SoulRuneConfigCategory>
    {
        private readonly Dictionary<int, SoulRuneConfig> _dataMap;
        private readonly List<SoulRuneConfig> _dataList;

        public SoulRuneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulRuneConfig>();
            _dataList = new List<SoulRuneConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulRuneConfig _v;
                _v = SoulRuneConfig.DeserializeSoulRuneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulRuneConfig> DataMap => _dataMap;
        public List<SoulRuneConfig> DataList => _dataList;

        public SoulRuneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulRuneConfig Get(int key) => _dataMap[key];
        public SoulRuneConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
