
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵等级属性配置
    /// </summary>
    [Config]
    public partial class SoulLevelConfigCategory : Singleton<SoulLevelConfigCategory>
    {
        private readonly List<SoulLevelConfig> _dataList;

        private Dictionary<(int, int), SoulLevelConfig> _dataMapUnion;

        public SoulLevelConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<SoulLevelConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                SoulLevelConfig _v;
                _v = SoulLevelConfig.DeserializeSoulLevelConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(int, int), SoulLevelConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.Id, _v.Level), _v);
            }
        }

        public List<SoulLevelConfig> DataList => _dataList;

        public SoulLevelConfig Get(int Id, int Level) => _dataMapUnion.TryGetValue((Id, Level), out SoulLevelConfig __v) ? __v : null;

        partial void PostInit();
    }
}
