
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵星级属性配置
    /// </summary>
    [Config]
    public partial class SoulStarConfigCategory : Singleton<SoulStarConfigCategory>
    {
        private readonly List<SoulStarConfig> _dataList;

        private Dictionary<(int, int), SoulStarConfig> _dataMapUnion;

        public SoulStarConfigCategory(ByteBuf _buf)
        {
            _dataList = new List<SoulStarConfig>();

            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                SoulStarConfig _v;
                _v = SoulStarConfig.DeserializeSoulStarConfig(_buf);
                _dataList.Add(_v);
            }
            _dataMapUnion = new Dictionary<(int, int), SoulStarConfig>();
            foreach(var _v in _dataList)
            {
                _dataMapUnion.Add((_v.Id, _v.Star), _v);
            }
        }

        public List<SoulStarConfig> DataList => _dataList;

        public SoulStarConfig Get(int Id, int Star) => _dataMapUnion.TryGetValue((Id, Star), out SoulStarConfig __v) ? __v : null;

        partial void PostInit();
    }
}
