
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SoulBuffConfig : BeanBase
    {
        public SoulBuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            BuffProperty = (BuffProperty)_buf.ReadInt();
            ContinueRound = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AddActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AddActions.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NewRoundActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NewRoundActions.Add(_e0);}}
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RemoveActions = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemoveActions.Add(_e0);}}

            PostInit();
        }

        public static SoulBuffConfig DeserializeSoulBuffConfig(ByteBuf _buf)
        {
            return new SoulBuffConfig(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// buff名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// buff描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// buff类型属性
        /// </summary>
        public readonly BuffProperty BuffProperty;

        /// <summary>
        /// 持续回合数
        /// </summary>
        public readonly int ContinueRound;

        /// <summary>
        /// buff添加行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> AddActions;

        /// <summary>
        /// buff新回合行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> NewRoundActions;

        /// <summary>
        /// buff移除行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> RemoveActions;

        public const int __ID__ = -1464729624;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "BuffProperty:" + BuffProperty + ","
            + "ContinueRound:" + ContinueRound + ","
            + "AddActions:" + Luban.StringUtil.CollectionToString(AddActions) + ","
            + "NewRoundActions:" + Luban.StringUtil.CollectionToString(NewRoundActions) + ","
            + "RemoveActions:" + Luban.StringUtil.CollectionToString(RemoveActions) + ","
            + "}";
        }

        partial void PostInit();
    }
}
