
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 灵天赋配置
    /// </summary>
    [Config]
    public partial class SoulTalentConfigCategory : Singleton<SoulTalentConfigCategory>
    {
        private readonly Dictionary<int, SoulTalentConfig> _dataMap;
        private readonly List<SoulTalentConfig> _dataList;

        public SoulTalentConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SoulTalentConfig>();
            _dataList = new List<SoulTalentConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SoulTalentConfig _v;
                _v = SoulTalentConfig.DeserializeSoulTalentConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SoulTalentConfig> DataMap => _dataMap;
        public List<SoulTalentConfig> DataList => _dataList;

        public SoulTalentConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public SoulTalentConfig Get(int key) => _dataMap[key];
        public SoulTalentConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
