
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SystemInfoConfig : BeanBase
    {
        public SystemInfoConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Content = _buf.ReadString();

            PostInit();
        }

        public static SystemInfoConfig DeserializeSystemInfoConfig(ByteBuf _buf)
        {
            return new SystemInfoConfig(_buf);
        }

        /// <summary>
        /// 系统提示id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 系统提示内容
        /// </summary>
        public readonly string Content;

        public const int __ID__ = -1107296961;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Content:" + Content + ","
            + "}";
        }

        partial void PostInit();
    }
}
