
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TalentConfig : BeanBase
    {
        public TalentConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            LevelLimit = _buf.ReadInt();
            MaxLevel = _buf.ReadInt();
            Consume = _buf.ReadInt();

            PostInit();
        }

        public static TalentConfig DeserializeTalentConfig(ByteBuf _buf)
        {
            return new TalentConfig(_buf);
        }

        /// <summary>
        /// 天赋id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 天赋名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 天赋描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 玩家等级限制
        /// </summary>
        public readonly int LevelLimit;

        /// <summary>
        /// 天赋最大等级
        /// </summary>
        public readonly int MaxLevel;

        /// <summary>
        /// 天赋每级消耗
        /// </summary>
        public readonly int Consume;

        public const int __ID__ = -1834609810;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Desc:" + Desc + ","
            + "LevelLimit:" + LevelLimit + ","
            + "MaxLevel:" + MaxLevel + ","
            + "Consume:" + Consume + ","
            + "}";
        }

        partial void PostInit();
    }
}
