
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 幻化配置
    /// </summary>
    [Config]
    public partial class TransmogrificationConfigCategory : Singleton<TransmogrificationConfigCategory>
    {
        private readonly Dictionary<int, TransmogrificationConfig> _dataMap;
        private readonly List<TransmogrificationConfig> _dataList;

        public TransmogrificationConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TransmogrificationConfig>();
            _dataList = new List<TransmogrificationConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TransmogrificationConfig _v;
                _v = TransmogrificationConfig.DeserializeTransmogrificationConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TransmogrificationConfig> DataMap => _dataMap;
        public List<TransmogrificationConfig> DataList => _dataList;

        public TransmogrificationConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public TransmogrificationConfig Get(int key) => _dataMap[key];
        public TransmogrificationConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
