
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TransmogrificationConfig : BeanBase
    {
        public TransmogrificationConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            TransConfig = _buf.ReadInt();
            Model = _buf.ReadString();

            PostInit();
        }

        public static TransmogrificationConfig DeserializeTransmogrificationConfig(ByteBuf _buf)
        {
            return new TransmogrificationConfig(_buf);
        }

        /// <summary>
        /// 装备编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 幻化编号
        /// </summary>
        public readonly int TransConfig;

        /// <summary>
        /// 幻化部件模型
        /// </summary>
        public readonly string Model;

        public const int __ID__ = -1345465845;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TransConfig:" + TransConfig + ","
            + "Model:" + Model + ","
            + "}";
        }

        partial void PostInit();
    }
}
