
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UIGroupType
    {
        /// <summary>
        /// 通用base修改（和通用变化不大）
        /// </summary>
        GeneralFixed = 1,

        /// <summary>
        /// 场景、玩法（和通用变化比较大）
        /// </summary>
        Base = 2,

        /// <summary>
        /// 常规组
        /// </summary>
        Normal = 3,

        /// <summary>
        /// 追加（例如弹出界面也参与界面回朔）
        /// </summary>
        Add = 4,

        /// <summary>
        /// 通用base
        /// </summary>
        GeneralBase = 99,

    }
}
