
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UnitType
    {
        /// <summary>
        /// 玩家
        /// </summary>
        UnitType_Player = 1,

        /// <summary>
        /// 怪物
        /// </summary>
        UnitType_Monster = 2,

        /// <summary>
        /// NPC
        /// </summary>
        UnitType_NPC = 3,

        /// <summary>
        /// 子弹
        /// </summary>
        UnitType_Bullet = 4,

    }
}
